"""
EAZR Existing API Discovery
============================
Complete mapping of every existing eazr_chat endpoint that Hibiscus agents call as tools.

This file is the BRIDGE between the existing EAZR backend (botproject/) and the new
Hibiscus AI engine (hibiscus/). Hibiscus agents DO NOT access databases directly —
they call these endpoints via HTTP through client.py.

HOW TO USE THIS FILE:
1. Each ExistingEndpoint describes one live API endpoint
2. client.py uses these definitions to generate typed tool functions
3. When building an agent, check AGENT_TOOL_MAP first
4. If a capability is missing, check MISSING_ENDPOINTS and add the route

LAST UPDATED: 2026-03-03
GENERATED BY: Full codebase analysis of botproject/ (routers/, services/, models/)
BASE URL: http://eazr-app:8000  (Docker internal) | http://localhost:8000 (local dev)
TOTAL ENDPOINTS DISCOVERED: 178
TOTAL SERVICES: 25
TOTAL MODELS: 16 files, 130+ Pydantic models
"""

from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any
from enum import Enum


class EndpointCategory(str, Enum):
    POLICY_EXTRACTION   = "policy_extraction"
    POLICY_ANALYSIS     = "policy_analysis"
    SCORING             = "scoring"
    REPORT_GENERATION   = "report_generation"
    COMPLIANCE          = "compliance"
    CHAT                = "chat"
    USER                = "user"
    AUTH                = "auth"
    POLICY_CRUD         = "policy_crud"
    IPF_SVF             = "ipf_svf"
    BILLING             = "billing"
    BENCHMARK           = "benchmark"
    PRODUCT             = "product"
    GAP_ANALYSIS        = "gap_analysis"
    RECOMMENDATION      = "recommendation"
    NOTIFICATION        = "notification"
    ADMIN               = "admin"
    HEALTH              = "health"
    CARDS               = "cards"
    REWARDS             = "rewards"
    LEGAL               = "legal"
    WEBSOCKET           = "websocket"


@dataclass
class EndpointParam:
    name: str
    type: str        # "str" | "int" | "float" | "file" | "dict" | "list" | "bool"
    required: bool
    description: str
    example: Any = None
    location: str = "body"   # "body" | "query" | "path" | "header" | "form"


@dataclass
class ExistingEndpoint:
    """Documents one existing API endpoint in the eazr_chat backend."""
    name: str
    category: EndpointCategory
    method: str                              # GET POST PUT DELETE PATCH WS
    path: str                                # Full path e.g. /api/policy/upload
    params: List[EndpointParam] = field(default_factory=list)
    request_body_schema: Optional[Dict[str, Any]] = None
    accepts_file: bool = False
    response_schema: Optional[Dict[str, Any]] = None
    response_description: str = ""
    auth_required: bool = True
    auth_type: str = "session"               # "session" | "jwt" | "admin" | "none" | "optional"
    is_async: bool = False
    typical_latency_ms: int = 500
    used_by_agents: List[str] = field(default_factory=list)
    router_file: str = ""
    service_file: str = ""
    notes: str = ""


# ═══════════════════════════════════════════════════════════════════════════════
# AUTH ENDPOINTS  (4)
# ═══════════════════════════════════════════════════════════════════════════════

AUTH_ENDPOINTS: List[ExistingEndpoint] = [

    ExistingEndpoint(
        name="send_otp",
        category=EndpointCategory.AUTH,
        method="POST", path="/send-otp",
        auth_required=False, auth_type="none",
        params=[EndpointParam("phone", "str", True, "Indian mobile number", "9876543210", "body")],
        response_description="{success, message}",
        typical_latency_ms=800,
        router_file="botproject/routers/auth.py",
        service_file="botproject/services/auth_service.py",
        notes="Rate limited: 3/min per IP + 3/hour per phone. Calls eazr.in OTP API.",
    ),

    ExistingEndpoint(
        name="verify_otp",
        category=EndpointCategory.AUTH,
        method="POST", path="/verify-otp",
        auth_required=False, auth_type="none",
        params=[
            EndpointParam("phone", "str", True, "Mobile number", location="body"),
            EndpointParam("otp", "str", True, "6-digit OTP", location="body"),
            EndpointParam("ip_address", "str", False, "Client IP", location="body"),
            EndpointParam("user_agent", "str", False, "User agent string", location="body"),
            EndpointParam("app_version", "str", False, "App version", location="body"),
        ],
        response_description="{success, session_id, chat_session_id, user_phone, access_token, user_id, profile_created}",
        typical_latency_ms=600,
        router_file="botproject/routers/auth.py",
        service_file="botproject/services/auth_service.py",
        notes="Rate: 5/min IP, 10/hour strict. Creates JWT + session_id in MongoDB.",
    ),

    ExistingEndpoint(
        name="oauth_login",
        category=EndpointCategory.AUTH,
        method="POST", path="/oauth-login",
        auth_required=False, auth_type="none",
        params=[
            EndpointParam("provider", "str", True, "google or apple", location="body"),
            EndpointParam("idToken", "str", True, "Provider ID token", location="body"),
            EndpointParam("ip_address", "str", False, "Client IP", location="body"),
            EndpointParam("user_agent", "str", False, "User agent", location="body"),
            EndpointParam("app_version", "str", False, "App version", location="body"),
        ],
        response_description="{success, session_id, access_token, user_id, email, provider}",
        typical_latency_ms=700,
        router_file="botproject/routers/auth.py",
        service_file="botproject/services/auth_service.py",
        notes="Rate: 10/min per IP. Supports Google and Apple OAuth.",
    ),

    ExistingEndpoint(
        name="check_session",
        category=EndpointCategory.AUTH,
        method="POST", path="/check-session",
        auth_required=False, auth_type="none",
        params=[EndpointParam("session_id", "str", True, "Session ID to validate", location="body")],
        response_description="{valid, message, session_id, user_phone}",
        typical_latency_ms=200,
        used_by_agents=["all"],
        router_file="botproject/routers/auth.py",
        service_file="botproject/services/auth_service.py",
        notes="Rate: 60/min. Validates + regenerates session if near expiry.",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# POLICY UPLOAD & EXTRACTION  (1 main + analysis endpoints)
# ═══════════════════════════════════════════════════════════════════════════════

POLICY_EXTRACTION_ENDPOINTS: List[ExistingEndpoint] = [

    ExistingEndpoint(
        name="upload_and_analyze_policy",
        category=EndpointCategory.POLICY_EXTRACTION,
        method="POST", path="/api/policy/upload",
        auth_required=True, auth_type="session",
        accepts_file=True,
        params=[
            EndpointParam("policyDocument", "file", True, "PDF policy document", location="form"),
            EndpointParam("userId", "str", True, "User ID", location="form"),
            EndpointParam("sessionId", "str", True, "Session ID", location="form"),
            EndpointParam("policyFor", "str", True, "self | family", location="form"),
            EndpointParam("name", "str", True, "Policy holder name", location="form"),
            EndpointParam("gender", "str", False, "male | female | other", location="form"),
            EndpointParam("relationship", "str", False, "self | spouse | father | mother | son | daughter", location="form"),
            EndpointParam("dateOfBirth", "str", False, "YYYY-MM-DD", location="form"),
            EndpointParam("uploadedAt", "str", False, "ISO timestamp", location="form"),
            EndpointParam("generate_pdf", "bool", False, "Generate PDF report", location="form"),
        ],
        response_description=(
            "{success, policyId, policy{policyNumber,uin,insuranceProvider,policyType,policyHolderName,"
            "sumAssured,premium,startDate,endDate,status}, classification{category,subcategory,confidence},"
            "scores{overall,coverage,value,trust,transparency}, verdict{overallVerdict}, zones, "
            "validation{dataQuality,fourChecks}, compliance, recommendations[], report{url}}"
        ),
        typical_latency_ms=45000,
        used_by_agents=["PolicyAnalyzer", "PortfolioOptimizer"],
        router_file="botproject/routers/policy_upload.py",
        service_file="botproject/policy_analysis/",
        notes=(
            "THE CORE ENDPOINT. Accepts PDF, runs 7-stage pipeline: "
            "extract→classify→score→zone→validate→comply→report. "
            "Supports health/life/motor/travel/PA. Rejects home/crop/business/marine. "
            "DeepSeek LLM for extraction. Rule-based scoring. Rate: 10/min. "
            "Stores result in MongoDB policy_analyses_collection."
        ),
    ),

    ExistingEndpoint(
        name="analyze_insurance_dynamic",
        category=EndpointCategory.POLICY_ANALYSIS,
        method="POST", path="/analyze-insurance-dynamic",
        auth_required=True, auth_type="session",
        accepts_file=True,
        params=[
            EndpointParam("files", "file", True, "PDF or image files", location="form"),
            EndpointParam("userId", "str", True, "User ID", location="form"),
            EndpointParam("sessionId", "str", True, "Session ID", location="form"),
            EndpointParam("generate_pdf", "bool", False, "Generate PDF report", location="form"),
        ],
        response_description="{success, analysis_result, report_url}",
        typical_latency_ms=40000,
        used_by_agents=["PolicyAnalyzer"],
        router_file="botproject/routers/policy.py",
        service_file="botproject/services/policy_service.py",
        notes="Alternative upload via chat flow. Also accepts images (.png/.jpg/.jpeg/.webp). Uploads to S3.",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# USER POLICIES (CRUD)  (3)
# ═══════════════════════════════════════════════════════════════════════════════

USER_POLICY_ENDPOINTS: List[ExistingEndpoint] = [

    ExistingEndpoint(
        name="get_user_policies",
        category=EndpointCategory.POLICY_CRUD,
        method="GET", path="/api/user/policies",
        auth_required=True, auth_type="optional",
        params=[
            EndpointParam("userId", "str", True, "User ID", location="query"),
            EndpointParam("category", "str", False, "Filter by category (health/life/motor/travel/pa)", location="query"),
            EndpointParam("status", "str", False, "Filter by status (active/expired/expiring_soon)", location="query"),
            EndpointParam("policyFor", "str", False, "self | family", location="query"),
        ],
        response_description=(
            "{success, userId, portfolioOverview{totalPolicies,activePolicies,totalCoverage,avgProtectionScore},"
            "portfolioBreakdown[], policies[{policyId,policyNumber,provider,category,holderName,"
            "premium,coverageAmount,status,expiryDate,protectionScore,gaps[]}]}"
        ),
        typical_latency_ms=400,
        used_by_agents=["PolicyAnalyzer", "PortfolioOptimizer", "TaxAdvisor", "RiskDetector"],
        router_file="botproject/routers/user_policies.py",
        notes="Key endpoint for portfolio view. Supports filtering by category/status/policyFor.",
    ),

    ExistingEndpoint(
        name="get_policy_detail",
        category=EndpointCategory.POLICY_CRUD,
        method="GET", path="/api/user/policies/{policyId}",
        auth_required=True, auth_type="optional",
        params=[
            EndpointParam("policyId", "str", True, "MongoDB ObjectId of policy", location="path"),
            EndpointParam("userId", "str", True, "User ID", location="query"),
        ],
        response_description=(
            "{success, policy{...full policy}, extraction_v2{...all extracted fields}, "
            "validation{dataQuality,fourChecks}, scores{overall,coverage,value,trust}, "
            "zones[{feature,zone,label,detail}], verdict{overallVerdict,score,summary}, "
            "compliance[{mandateId,name,passed,status}], recommendations[], gaps[]}"
        ),
        typical_latency_ms=300,
        used_by_agents=["PolicyAnalyzer", "ClaimsGuide", "TaxAdvisor", "RiskDetector", "Recommender", "PortfolioOptimizer"],
        router_file="botproject/routers/user_policies.py",
        notes="MOST USEFUL for agents. Returns complete policy with all analysis layers.",
    ),

    ExistingEndpoint(
        name="remove_policy",
        category=EndpointCategory.POLICY_CRUD,
        method="POST", path="/api/policy/remove",
        auth_required=True, auth_type="optional",
        params=[
            EndpointParam("policyId", "str", True, "Policy ID to remove", location="body"),
            EndpointParam("userId", "str", True, "User ID", location="body"),
        ],
        response_description="{success, message, policyId, userId, deletedAt}",
        typical_latency_ms=250,
        router_file="botproject/routers/user_policies.py",
        notes="Soft delete — sets deleted flag in MongoDB.",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# POLICY LOCKER  (22 endpoints)
# ═══════════════════════════════════════════════════════════════════════════════

POLICY_LOCKER_ENDPOINTS: List[ExistingEndpoint] = [

    ExistingEndpoint(
        name="get_locker_summary",
        category=EndpointCategory.POLICY_CRUD,
        method="GET", path="/api/v1/policy-locker/summary",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("session_id", "str", True, "Session ID", location="query"),
            EndpointParam("user_id", "str", True, "User ID", location="query"),
        ],
        response_description="{success, data{totalPolicies,activePolicies,expiringPolicies,totalCoverage,avgProtectionScore}}",
        typical_latency_ms=300,
        used_by_agents=["PortfolioOptimizer", "PolicyAnalyzer"],
        router_file="botproject/routers/policy_locker.py",
        service_file="botproject/services/policy_locker_service.py",
    ),

    ExistingEndpoint(
        name="get_self_policies",
        category=EndpointCategory.POLICY_CRUD,
        method="GET", path="/api/v1/policy-locker/policies/self",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("session_id", "str", True, "Session ID", location="query"),
            EndpointParam("user_id", "str", True, "User ID", location="query"),
        ],
        response_description="{success, data[{policyId,policyNumber,provider,category,status,premium,coverage,score}]}",
        typical_latency_ms=350,
        used_by_agents=["PortfolioOptimizer", "PolicyAnalyzer", "TaxAdvisor"],
        router_file="botproject/routers/policy_locker.py",
    ),

    ExistingEndpoint(
        name="get_family_policies",
        category=EndpointCategory.POLICY_CRUD,
        method="GET", path="/api/v1/policy-locker/policies/family",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("session_id", "str", True, "Session ID", location="query"),
            EndpointParam("user_id", "str", True, "User ID", location="query"),
        ],
        response_description="{success, data{familyMembers[{memberName,relationship,policies[]}]}}",
        typical_latency_ms=400,
        used_by_agents=["PortfolioOptimizer", "Recommender"],
        router_file="botproject/routers/policy_locker.py",
    ),

    ExistingEndpoint(
        name="get_family_members",
        category=EndpointCategory.USER,
        method="GET", path="/api/v1/policy-locker/family-members",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("session_id", "str", True, "Session ID", location="query"),
            EndpointParam("user_id", "str", True, "User ID", location="query"),
        ],
        response_description="{success, data[{memberId,name,relationship,dob,gender,policies[]}]}",
        typical_latency_ms=250,
        used_by_agents=["PortfolioOptimizer", "Recommender"],
        router_file="botproject/routers/policy_locker.py",
    ),

    ExistingEndpoint(
        name="update_family_member",
        category=EndpointCategory.USER,
        method="PUT", path="/api/v1/policy-locker/family-members/{member_id}",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("member_id", "str", True, "Member ID", location="path"),
            EndpointParam("session_id", "str", True, "Session ID", location="body"),
            EndpointParam("user_id", "str", True, "User ID", location="body"),
            EndpointParam("name", "str", False, "Member name", location="body"),
            EndpointParam("relationship", "str", False, "Relationship", location="body"),
            EndpointParam("dateOfBirth", "str", False, "DOB YYYY-MM-DD", location="body"),
            EndpointParam("gender", "str", False, "male|female|other", location="body"),
        ],
        response_description="{success, data{...updated member}}",
        typical_latency_ms=300,
        router_file="botproject/routers/policy_locker.py",
    ),

    ExistingEndpoint(
        name="analyze_locker_policy",
        category=EndpointCategory.POLICY_ANALYSIS,
        method="POST", path="/api/v1/policy-locker/policies/{policy_id}/analyze",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("policy_id", "str", True, "Policy ID", location="path"),
            EndpointParam("session_id", "str", True, "Session ID", location="body"),
            EndpointParam("user_id", "str", True, "User ID", location="body"),
        ],
        response_description="{success, data{analysis,scores,gaps,recommendations}}",
        typical_latency_ms=5000,
        used_by_agents=["PolicyAnalyzer", "RiskDetector"],
        router_file="botproject/routers/policy_locker.py",
    ),

    ExistingEndpoint(
        name="confirm_locker_policy",
        category=EndpointCategory.POLICY_CRUD,
        method="POST", path="/api/v1/policy-locker/policies/{policy_id}/confirm",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("policy_id", "str", True, "Policy ID", location="path"),
            EndpointParam("session_id", "str", True, "Session ID", location="body"),
            EndpointParam("user_id", "str", True, "User ID", location="body"),
        ],
        response_description="{success, data{confirmed, policyId}}",
        typical_latency_ms=300,
        router_file="botproject/routers/policy_locker.py",
    ),

    ExistingEndpoint(
        name="get_claim_details",
        category=EndpointCategory.POLICY_CRUD,
        method="GET", path="/api/v1/policy-locker/claims/{claim_id}",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("claim_id", "str", True, "Claim ID", location="path"),
            EndpointParam("session_id", "str", True, "Session ID", location="query"),
            EndpointParam("user_id", "str", True, "User ID", location="query"),
        ],
        response_description="{success, data{claimId,claimNumber,status,nextSteps[],timeline[]}}",
        typical_latency_ms=250,
        used_by_agents=["ClaimsGuide"],
        router_file="botproject/routers/policy_locker.py",
    ),

    ExistingEndpoint(
        name="get_emergency_services",
        category=EndpointCategory.POLICY_CRUD,
        method="GET", path="/api/v1/policy-locker/emergency-services",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("session_id", "str", True, "Session ID", location="query"),
            EndpointParam("user_id", "str", True, "User ID", location="query"),
        ],
        response_description="{success, data{emergencyContacts[{name,phone,type}], nearbyHospitals[]}}",
        typical_latency_ms=300,
        used_by_agents=["ClaimsGuide", "GrievanceNavigator"],
        router_file="botproject/routers/policy_locker.py",
    ),

    ExistingEndpoint(
        name="share_policy",
        category=EndpointCategory.POLICY_CRUD,
        method="POST", path="/api/v1/policy-locker/policies/{policy_id}/share",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("policy_id", "str", True, "Policy ID", location="path"),
            EndpointParam("method", "str", True, "email|link|print", location="body"),
            EndpointParam("email", "str", False, "Target email", location="body"),
            EndpointParam("expiryHours", "int", False, "Link expiry in hours", location="body"),
        ],
        response_description="{success, data{shareUrl, expiresAt}}",
        typical_latency_ms=500,
        router_file="botproject/routers/policy_locker.py",
    ),

    ExistingEndpoint(
        name="export_policy",
        category=EndpointCategory.POLICY_CRUD,
        method="GET", path="/api/v1/policy-locker/policies/{policy_id}/export",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("policy_id", "str", True, "Policy ID", location="path"),
            EndpointParam("session_id", "str", True, "Session ID", location="query"),
            EndpointParam("user_id", "str", True, "User ID", location="query"),
        ],
        response_description="{success, data{downloadUrl, expiresAt}}",
        typical_latency_ms=2000,
        router_file="botproject/routers/policy_locker.py",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# CHAT  (12 endpoints + 1 WebSocket)
# ═══════════════════════════════════════════════════════════════════════════════

CHAT_ENDPOINTS: List[ExistingEndpoint] = [

    ExistingEndpoint(
        name="ask_chat",
        category=EndpointCategory.CHAT,
        method="POST", path="/api/ask",
        auth_required=True, auth_type="session",
        accepts_file=True,
        params=[
            EndpointParam("user_session_id", "str", True, "Session ID", location="body"),
            EndpointParam("access_token", "str", True, "JWT token", location="body"),
            EndpointParam("user_id", "str", True, "User ID", location="body"),
            EndpointParam("query", "str", False, "User message", location="body"),
            EndpointParam("action", "str", False, "Action type for structured flows", location="body"),
            EndpointParam("insurance_type", "str", False, "health|life|motor|travel|pa", location="body"),
            EndpointParam("files", "file", False, "Optional file attachment", location="form"),
        ],
        response_description="{success, response, intent, action, suggestions[], session_id, message_id}",
        typical_latency_ms=3000,
        used_by_agents=["all - this is LEGACY; Hibiscus replaces this"],
        router_file="botproject/routers/chat.py",
        service_file="botproject/services/authenticated_chat_handler.py",
        notes=(
            "LEGACY endpoint — Hibiscus replaces this with POST /hibiscus/chat. "
            "Intent routing: financial_assistance → action_handler, insurance_analysis → analyzer, "
            "rag_query → report_rag_handler, claim → policy_service, casual → LLM direct."
        ),
    ),

    ExistingEndpoint(
        name="new_chat_session",
        category=EndpointCategory.CHAT,
        method="POST", path="/api/new-chat",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("session_id", "str", True, "Auth session", location="body"),
            EndpointParam("title", "str", False, "Chat title", location="body"),
        ],
        response_description="{success, chat_session_id, title}",
        typical_latency_ms=200,
        router_file="botproject/routers/chat.py",
        service_file="botproject/services/chat_service.py",
    ),

    ExistingEndpoint(
        name="load_chat",
        category=EndpointCategory.CHAT,
        method="GET", path="/api/load-chat/{session_id}",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("session_id", "str", True, "Chat session ID", location="path"),
            EndpointParam("user_id", "str", True, "User ID", location="query"),
            EndpointParam("limit", "int", False, "Message limit (default 50)", location="query"),
        ],
        response_description="{success, session_info, messages[{role,content,timestamp,intent}]}",
        typical_latency_ms=300,
        router_file="botproject/routers/chat.py",
        service_file="botproject/services/chat_service.py",
    ),

    ExistingEndpoint(
        name="get_chat_history",
        category=EndpointCategory.CHAT,
        method="POST", path="/api/chat-history",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("session_id", "str", True, "Auth session", location="body"),
            EndpointParam("user_id", "str", True, "User ID", location="body"),
            EndpointParam("limit", "int", False, "Items per page", location="body"),
        ],
        response_description="{success, organized_chats{today[], yesterday[], last_7_days[], last_30_days[], older[]}}",
        typical_latency_ms=350,
        router_file="botproject/routers/chat.py",
    ),

    ExistingEndpoint(
        name="search_chats",
        category=EndpointCategory.CHAT,
        method="POST", path="/api/search-chats",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("session_id", "str", True, "Auth session", location="body"),
            EndpointParam("user_id", "str", True, "User ID", location="body"),
            EndpointParam("query", "str", True, "Search query", location="body"),
            EndpointParam("limit", "int", False, "Max results", location="body"),
        ],
        response_description="{success, results[{chat_session_id,title,snippet,timestamp}]}",
        typical_latency_ms=400,
        router_file="botproject/routers/chat.py",
    ),

    ExistingEndpoint(
        name="clear_chat_history",
        category=EndpointCategory.CHAT,
        method="POST", path="/api/clear-user-chat-history",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("session_id", "str", True, "Auth session", location="body"),
            EndpointParam("user_id", "str", True, "User ID", location="body"),
            EndpointParam("confirm", "bool", True, "Must be true", location="body"),
        ],
        response_description="{success, message, backed_up_count}",
        typical_latency_ms=500,
        router_file="botproject/routers/chat.py",
        notes="Backs up to MongoDB backup_sessions before clearing.",
    ),

    ExistingEndpoint(
        name="websocket_chat",
        category=EndpointCategory.WEBSOCKET,
        method="WS", path="/ws/chat",
        auth_required=True, auth_type="jwt",
        params=[
            EndpointParam("token", "str", True, "JWT token", location="query"),
            EndpointParam("session_id", "str", False, "Session ID", location="query"),
            EndpointParam("device_id", "str", False, "Device ID", location="query"),
        ],
        response_description="Streaming JSON: {type, content, intent, message_id, is_complete}",
        typical_latency_ms=100,
        used_by_agents=["all - streaming interface"],
        router_file="botproject/routers/websocket_chat.py",
        service_file="botproject/services/websocket_chat_service.py",
        notes=(
            "Real-time streaming via LangGraph. Message types: authenticate, chat, typing, presence, leave. "
            "Supports typing indicators. Hibiscus will use this interface for streaming responses."
        ),
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# CLAIM GUIDANCE  (1)
# ═══════════════════════════════════════════════════════════════════════════════

CLAIM_ENDPOINTS: List[ExistingEndpoint] = [

    ExistingEndpoint(
        name="get_claim_guidance",
        category=EndpointCategory.POLICY_ANALYSIS,
        method="POST", path="/insurance-claim-guidance",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("query", "str", True, "User's claim question", location="body"),
            EndpointParam("session_id", "str", True, "Auth session", location="body"),
            EndpointParam("access_token", "str", True, "JWT token", location="body"),
            EndpointParam("user_id", "str", True, "User ID", location="body"),
            EndpointParam("insurance_type", "str", False, "health|life|motor|travel|pa", location="body"),
        ],
        response_description="{success, response, action, suggestions[], context_used}",
        typical_latency_ms=4000,
        used_by_agents=["ClaimsGuide"],
        router_file="botproject/routers/policy.py",
        service_file="botproject/services/policy_service.py",
        notes="Detects claim keywords. LLM generates step-by-step guidance. Stores in claim_guidance_collection.",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# DASHBOARD & PORTFOLIO  (5)
# ═══════════════════════════════════════════════════════════════════════════════

DASHBOARD_ENDPOINTS: List[ExistingEndpoint] = [

    ExistingEndpoint(
        name="get_protection_score",
        category=EndpointCategory.SCORING,
        method="GET", path="/api/dashboard/protection-score/{user_id}",
        auth_required=True, auth_type="jwt",
        params=[
            EndpointParam("user_id", "str", True, "User ID", location="path"),
            EndpointParam("annualIncome", "int", False, "Annual income in INR", location="header"),
        ],
        response_description="{success, overallScore, breakdown{health,life,motor,travel}, verdict, recommendations[]}",
        typical_latency_ms=800,
        used_by_agents=["PortfolioOptimizer", "Calculator", "RiskDetector"],
        router_file="botproject/routers/dashboard.py",
        service_file="botproject/services/protection_score_calculator.py",
        notes="Pure algorithmic score (0-100). No LLM. Verdicts: Excellent/Strong/Adequate/Moderate/Needs Attention.",
    ),

    ExistingEndpoint(
        name="refresh_protection_score",
        category=EndpointCategory.SCORING,
        method="POST", path="/api/dashboard/refresh-score",
        auth_required=True, auth_type="jwt",
        params=[
            EndpointParam("annualIncome", "int", False, "Updated annual income", location="body"),
            EndpointParam("reason", "str", False, "Reason for refresh", location="body"),
        ],
        response_description="{success, newScore, previousScore, delta, breakdown}",
        typical_latency_ms=1000,
        used_by_agents=["PortfolioOptimizer", "Calculator"],
        router_file="botproject/routers/dashboard.py",
    ),

    ExistingEndpoint(
        name="get_dashboard_insights",
        category=EndpointCategory.RECOMMENDATION,
        method="GET", path="/api/dashboard/insights",
        auth_required=True, auth_type="jwt",
        params=[EndpointParam("user_id", "str", True, "User ID", location="query")],
        response_description="{success, insights[{type,title,description,priority,action}]}",
        typical_latency_ms=600,
        used_by_agents=["PortfolioOptimizer", "Recommender"],
        router_file="botproject/routers/dashboard.py",
    ),

    ExistingEndpoint(
        name="get_renewals",
        category=EndpointCategory.POLICY_CRUD,
        method="GET", path="/api/dashboard/renewals",
        auth_required=True, auth_type="jwt",
        params=[EndpointParam("user_id", "str", True, "User ID", location="query")],
        response_description="{success, renewals[{policyId,provider,daysUntilExpiry,currentPremium,renewalPremium}]}",
        typical_latency_ms=400,
        used_by_agents=["PortfolioOptimizer", "Recommender"],
        router_file="botproject/routers/dashboard.py",
    ),

    ExistingEndpoint(
        name="get_portfolio_breakdown",
        category=EndpointCategory.SCORING,
        method="GET", path="/api/portfolio/breakdown",
        auth_required=True, auth_type="optional",
        params=[EndpointParam("userId", "str", True, "User ID", location="query")],
        response_description="{success, userId, portfolioOverview, categoryBreakdown[{category,icon,color,policyCount,coverage,percentage}]}",
        typical_latency_ms=350,
        used_by_agents=["PortfolioOptimizer", "Calculator"],
        router_file="botproject/routers/portfolio_breakdown.py",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# FAMILY MEMBERS  (1)
# ═══════════════════════════════════════════════════════════════════════════════

FAMILY_ENDPOINTS: List[ExistingEndpoint] = [

    ExistingEndpoint(
        name="get_family_coverage",
        category=EndpointCategory.USER,
        method="GET", path="/api/family/members",
        auth_required=True, auth_type="optional",
        params=[EndpointParam("userId", "str", True, "User ID", location="query")],
        response_description=(
            "{success, userId, totalMembers, totalPolicies, totalOverallCoverage, "
            "familyMembers[{memberName,relationship,emoji,policyCount,totalCoverage,policies[]}]}"
        ),
        typical_latency_ms=450,
        used_by_agents=["PortfolioOptimizer", "Recommender", "TaxAdvisor"],
        router_file="botproject/routers/family_members.py",
        notes="Groups policies by family member. Good for family floater gap analysis.",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# BILL AUDIT  (6)
# ═══════════════════════════════════════════════════════════════════════════════

BILL_AUDIT_ENDPOINTS: List[ExistingEndpoint] = [

    ExistingEndpoint(
        name="upload_bill",
        category=EndpointCategory.BILLING,
        method="POST", path="/api/v1/bill-audit/upload",
        auth_required=True, auth_type="session",
        accepts_file=True,
        params=[
            EndpointParam("session_id", "str", True, "Session ID", location="form"),
            EndpointParam("user_id", "str", True, "User ID", location="form"),
            EndpointParam("files", "file", True, "Bill images or PDFs (max 10)", location="form"),
            EndpointParam("policy_id", "str", False, "Associated policy ID", location="form"),
        ],
        response_description="{success, data{auditId, status, discrepancies[], savings{total,high_confidence,medium_confidence}, healthScore}}",
        typical_latency_ms=30000,
        used_by_agents=["ClaimsGuide"],
        router_file="botproject/routers/bill_audit.py",
        service_file="botproject/services/bill_audit_service.py",
        notes="Accepts JPEG/PNG/PDF. Max 10 files. Uses LLM (BillAuditAnalyzer) for extraction + discrepancy detection.",
    ),

    ExistingEndpoint(
        name="get_bill_audit_result",
        category=EndpointCategory.BILLING,
        method="GET", path="/api/v1/bill-audit/{audit_id}",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("audit_id", "str", True, "Audit ID", location="path"),
            EndpointParam("session_id", "str", True, "Session ID", location="query"),
            EndpointParam("user_id", "str", True, "User ID", location="query"),
        ],
        response_description="{success, data{...full audit result with discrepancies, savings, patient details}}",
        typical_latency_ms=300,
        used_by_agents=["ClaimsGuide"],
        router_file="botproject/routers/bill_audit.py",
    ),

    ExistingEndpoint(
        name="get_bill_audit_history",
        category=EndpointCategory.BILLING,
        method="GET", path="/api/v1/bill-audit/history/list",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("session_id", "str", True, "Session ID", location="query"),
            EndpointParam("user_id", "str", True, "User ID", location="query"),
            EndpointParam("limit", "int", False, "Page size", location="query"),
            EndpointParam("offset", "int", False, "Page offset", location="query"),
        ],
        response_description="{success, data{audits[], total, hasMore}}",
        typical_latency_ms=350,
        router_file="botproject/routers/bill_audit.py",
    ),

    ExistingEndpoint(
        name="generate_bill_audit_report",
        category=EndpointCategory.REPORT_GENERATION,
        method="POST", path="/api/v1/bill-audit/{audit_id}/report",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("audit_id", "str", True, "Audit ID", location="path"),
            EndpointParam("session_id", "str", True, "Session ID", location="form"),
            EndpointParam("user_id", "str", True, "User ID", location="form"),
        ],
        response_description="{success, data{report_url}}",
        typical_latency_ms=5000,
        used_by_agents=["ClaimsGuide"],
        router_file="botproject/routers/bill_audit.py",
    ),

    ExistingEndpoint(
        name="generate_dispute_letter",
        category=EndpointCategory.BILLING,
        method="POST", path="/api/v1/bill-audit/{audit_id}/dispute-letter",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("audit_id", "str", True, "Audit ID", location="path"),
            EndpointParam("session_id", "str", True, "Session ID", location="form"),
            EndpointParam("user_id", "str", True, "User ID", location="form"),
            EndpointParam("include_pdf", "bool", False, "Include PDF attachment", location="form"),
        ],
        response_description="{success, data{letter_text, pdf_url}}",
        typical_latency_ms=8000,
        used_by_agents=["ClaimsGuide", "GrievanceNavigator"],
        router_file="botproject/routers/bill_audit.py",
        notes="Generates formal dispute letter using LLM based on identified discrepancies.",
    ),

    ExistingEndpoint(
        name="bill_audit_health_check",
        category=EndpointCategory.HEALTH,
        method="GET", path="/api/v1/bill-audit/test",
        auth_required=True, auth_type="session",
        response_description="{success: true}",
        typical_latency_ms=50,
        router_file="botproject/routers/bill_audit.py",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# HBF — HOSPITAL/GARAGE BILL FINANCING  (6)
# ═══════════════════════════════════════════════════════════════════════════════

HBF_ENDPOINTS: List[ExistingEndpoint] = [

    ExistingEndpoint(
        name="check_hbf_eligibility",
        category=EndpointCategory.IPF_SVF,
        method="POST", path="/api/v1/hbf/eligibility",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("session_id", "str", True, "Session ID", location="body"),
            EndpointParam("user_id", "str", True, "User ID", location="body"),
            EndpointParam("loan_type", "str", True, "HBF", location="body"),
            EndpointParam("amount", "float", True, "Loan amount in INR", location="body"),
            EndpointParam("audit_id", "str", False, "Linked bill audit ID", location="body"),
        ],
        response_description="{success, data{eligible, reason, maxLoanAmount, loanId}}",
        typical_latency_ms=1500,
        used_by_agents=["ClaimsGuide"],
        router_file="botproject/routers/hbf.py",
        service_file="botproject/services/hbf_service.py",
        notes="Hospital Bill Financing eligibility check.",
    ),

    ExistingEndpoint(
        name="get_hbf_offers",
        category=EndpointCategory.IPF_SVF,
        method="POST", path="/api/v1/hbf/offers",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("session_id", "str", True, "Session ID", location="body"),
            EndpointParam("user_id", "str", True, "User ID", location="body"),
            EndpointParam("loan_id", "str", True, "Loan ID from eligibility", location="body"),
        ],
        response_description="{success, data{offers[{offerId,tenure,emi,interestRate,processingFee}]}}",
        typical_latency_ms=2000,
        used_by_agents=["ClaimsGuide"],
        router_file="botproject/routers/hbf.py",
    ),

    ExistingEndpoint(
        name="apply_hbf_loan",
        category=EndpointCategory.IPF_SVF,
        method="POST", path="/api/v1/hbf/apply",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("session_id", "str", True, "Session ID", location="body"),
            EndpointParam("user_id", "str", True, "User ID", location="body"),
            EndpointParam("loan_id", "str", True, "Loan ID", location="body"),
            EndpointParam("selected_offer_id", "str", True, "Chosen offer ID", location="body"),
        ],
        response_description="{success, data{applicationId, status, nextSteps[]}}",
        typical_latency_ms=3000,
        router_file="botproject/routers/hbf.py",
    ),

    ExistingEndpoint(
        name="get_hbf_loan_status",
        category=EndpointCategory.IPF_SVF,
        method="POST", path="/api/v1/hbf/status",
        auth_required=True, auth_type="session",
        params=[
            EndpointParam("session_id", "str", True, "Session ID", location="body"),
            EndpointParam("user_id", "str", True, "User ID", location="body"),
            EndpointParam("loan_id", "str", True, "Loan ID", location="body"),
        ],
        response_description="{success, data{loanId, status, disbursedAmount, emiSchedule[]}}",
        typical_latency_ms=500,
        router_file="botproject/routers/hbf.py",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# CARDS  (19)
# ═══════════════════════════════════════════════════════════════════════════════

CARD_ENDPOINTS: List[ExistingEndpoint] = [

    ExistingEndpoint(
        name="get_credit_banks", category=EndpointCategory.CARDS,
        method="GET", path="/cards/credit/banks",
        auth_required=False, auth_type="none",
        response_description="[{bankName, cardCount}]",
        typical_latency_ms=100,
        router_file="botproject/routers/cards.py",
        service_file="botproject/services/card_service.py",
    ),
    ExistingEndpoint(
        name="get_credit_cards", category=EndpointCategory.CARDS,
        method="GET", path="/cards/credit/cards",
        auth_required=False, auth_type="none",
        params=[
            EndpointParam("skip", "int", False, "Offset", location="query"),
            EndpointParam("limit", "int", False, "Max 100", location="query"),
        ],
        response_description="[{cardId, name, bank, benefits[], insuranceCover}]",
        typical_latency_ms=150,
        router_file="botproject/routers/cards.py",
    ),
    ExistingEndpoint(
        name="search_credit_cards", category=EndpointCategory.CARDS,
        method="GET", path="/cards/credit/search",
        auth_required=False, auth_type="none",
        params=[EndpointParam("q", "str", True, "Search query (min 2 chars)", location="query")],
        response_description="[{cardId, name, bank, benefits[]}]",
        typical_latency_ms=200,
        used_by_agents=["Recommender"],
        router_file="botproject/routers/cards.py",
    ),
    ExistingEndpoint(
        name="bin_lookup", category=EndpointCategory.CARDS,
        method="POST", path="/cards/bin/lookup",
        auth_required=False, auth_type="none",
        params=[
            EndpointParam("bin_number", "str", True, "First 6 digits of card", location="body"),
            EndpointParam("user_id", "str", True, "User ID", location="body"),
        ],
        response_description="{binInfo{bank,scheme,type}, matchingCards[]}",
        typical_latency_ms=300,
        router_file="botproject/routers/cards.py",
    ),
    ExistingEndpoint(
        name="get_card_benefits", category=EndpointCategory.CARDS,
        method="GET", path="/cards/benefits/{card_id}",
        auth_required=False, auth_type="none",
        params=[EndpointParam("card_id", "str", True, "Card ID", location="path")],
        response_description="{cardId, benefits[], insuranceBenefits{type, cover, terms[]}}",
        typical_latency_ms=150,
        used_by_agents=["Recommender", "PolicyAnalyzer"],
        router_file="botproject/routers/cards.py",
        notes="Key endpoint — credit card embedded insurance benefits (travel, PA, etc.).",
    ),
    ExistingEndpoint(
        name="get_user_cards", category=EndpointCategory.CARDS,
        method="GET", path="/cards/user/{user_id}",
        auth_required=False, auth_type="none",
        params=[
            EndpointParam("user_id", "str", True, "User ID", location="path"),
            EndpointParam("card_for", "str", False, "self|family", location="query"),
        ],
        response_description="{cards[{cardId,name,bank,last4,scheme,benefits[]}]}",
        typical_latency_ms=200,
        used_by_agents=["PortfolioOptimizer", "Recommender"],
        router_file="botproject/routers/cards.py",
        notes="Returns user's linked cards with their insurance benefits for portfolio analysis.",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# USER PROFILE  (1)
# ═══════════════════════════════════════════════════════════════════════════════

USER_ENDPOINTS: List[ExistingEndpoint] = [

    ExistingEndpoint(
        name="get_user_profile",
        category=EndpointCategory.USER,
        method="GET", path="/user-profile/{session_id}",
        auth_required=True, auth_type="session",
        params=[EndpointParam("session_id", "str", True, "Auth session ID", location="path")],
        response_description=(
            "{success, user{userId,phone,name,email,dob,gender,age,profileCompletion,"
            "preferences,chatSessions[],createdAt}, session_id}"
        ),
        typical_latency_ms=350,
        used_by_agents=["PolicyAnalyzer", "PortfolioOptimizer", "TaxAdvisor", "Recommender"],
        router_file="botproject/routers/user.py",
        service_file="botproject/services/user_service.py",
        notes="Returns profile completion score (0-100). Auto session regeneration if expired.",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# NOTIFICATIONS  (11)
# ═══════════════════════════════════════════════════════════════════════════════

NOTIFICATION_ENDPOINTS: List[ExistingEndpoint] = [

    ExistingEndpoint(
        name="register_device_token",
        category=EndpointCategory.NOTIFICATION,
        method="POST", path="/notifications/register-device",
        auth_required=False, auth_type="none",
        params=[
            EndpointParam("user_id", "str", True, "User ID", location="body"),
            EndpointParam("fcm_token", "str", True, "Firebase FCM token", location="body"),
            EndpointParam("device_type", "str", True, "ios|android", location="body"),
            EndpointParam("device_name", "str", False, "Device name", location="body"),
            EndpointParam("app_version", "str", False, "App version", location="body"),
        ],
        response_description="{success, message, device_id}",
        typical_latency_ms=300,
        router_file="botproject/routers/notifications.py",
        service_file="botproject/services/notification_service.py",
    ),

    ExistingEndpoint(
        name="get_notification_history",
        category=EndpointCategory.NOTIFICATION,
        method="GET", path="/notifications/history",
        auth_required=False, auth_type="none",
        params=[
            EndpointParam("user_id", "str", True, "User ID", location="query"),
            EndpointParam("limit", "int", False, "Max items", location="query"),
            EndpointParam("offset", "int", False, "Offset", location="query"),
            EndpointParam("unread_only", "bool", False, "Only unread", location="query"),
        ],
        response_description="{success, notifications[], total, unread_count}",
        typical_latency_ms=300,
        router_file="botproject/routers/notifications.py",
    ),

    ExistingEndpoint(
        name="mark_notification_read",
        category=EndpointCategory.NOTIFICATION,
        method="POST", path="/notifications/mark-read",
        auth_required=False, auth_type="none",
        params=[
            EndpointParam("user_id", "str", True, "User ID", location="body"),
            EndpointParam("notification_id", "str", True, "Notification ID", location="body"),
        ],
        response_description="{success}",
        typical_latency_ms=150,
        router_file="botproject/routers/notifications.py",
    ),

    ExistingEndpoint(
        name="get_notification_settings",
        category=EndpointCategory.NOTIFICATION,
        method="GET", path="/notifications/settings",
        auth_required=False, auth_type="none",
        params=[EndpointParam("user_id", "str", True, "User ID", location="query")],
        response_description="{policy_renewal, policy_expiry, claim_updates, payment_reminders, protection_score, recommendations, promotional}",
        typical_latency_ms=200,
        router_file="botproject/routers/notifications.py",
    ),

    ExistingEndpoint(
        name="update_notification_settings",
        category=EndpointCategory.NOTIFICATION,
        method="PUT", path="/notifications/settings",
        auth_required=False, auth_type="none",
        params=[
            EndpointParam("user_id", "str", True, "User ID", location="body"),
            EndpointParam("policy_renewal", "bool", False, "Toggle", location="body"),
            EndpointParam("claim_updates", "bool", False, "Toggle", location="body"),
        ],
        response_description="{success, updated_settings}",
        typical_latency_ms=250,
        router_file="botproject/routers/notifications.py",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# HEALTH  (4)
# ═══════════════════════════════════════════════════════════════════════════════

HEALTH_ENDPOINTS: List[ExistingEndpoint] = [

    ExistingEndpoint(
        name="health_check",
        category=EndpointCategory.HEALTH,
        method="GET", path="/health",
        auth_required=False, auth_type="none",
        response_description="{status, timestamp, service, version}",
        typical_latency_ms=50,
        router_file="botproject/routers/health.py",
    ),
    ExistingEndpoint(
        name="enhanced_health",
        category=EndpointCategory.HEALTH,
        method="GET", path="/enhanced-health",
        auth_required=False, auth_type="none",
        response_description="{status, services{redis, mongodb, langgraph, voice, multilingual}, storage, memory}",
        typical_latency_ms=300,
        router_file="botproject/routers/health.py",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# REWARDS  (3)
# ═══════════════════════════════════════════════════════════════════════════════

REWARDS_ENDPOINTS: List[ExistingEndpoint] = [

    ExistingEndpoint(
        name="get_rewards_progress",
        category=EndpointCategory.REWARDS,
        method="GET", path="/rewards/progress",
        auth_required=True, auth_type="optional",
        params=[EndpointParam("userId", "str", False, "User ID", location="query")],
        response_description="{success, data{requiredPolicies, uploadedPolicies, isUnlocked, isClaimed, reward}}",
        typical_latency_ms=300,
        used_by_agents=["Recommender"],
        router_file="botproject/routers/rewards.py",
        notes="Reward: Free ₹50,000 PA insurance for uploading 5 active policies.",
    ),
    ExistingEndpoint(
        name="check_reward_eligibility",
        category=EndpointCategory.REWARDS,
        method="GET", path="/rewards/eligibility",
        auth_required=True, auth_type="optional",
        params=[EndpointParam("userId", "str", False, "User ID", location="query")],
        response_description="{success, data{isEligible, isClaimed, reason, eligibleSince, claimedAt}}",
        typical_latency_ms=250,
        router_file="botproject/routers/rewards.py",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# LEGAL  (2)
# ═══════════════════════════════════════════════════════════════════════════════

LEGAL_ENDPOINTS: List[ExistingEndpoint] = [

    ExistingEndpoint(
        name="get_privacy_policy",
        category=EndpointCategory.LEGAL,
        method="GET", path="/api/privacy-policy",
        auth_required=False, auth_type="none",
        response_description="{success, data{content, url}}",
        typical_latency_ms=100,
        used_by_agents=["RegulationEngine"],
        router_file="botproject/routers/legal.py",
    ),
    ExistingEndpoint(
        name="get_terms_and_conditions",
        category=EndpointCategory.LEGAL,
        method="GET", path="/api/terms-and-conditions",
        auth_required=False, auth_type="none",
        response_description="{success, data{content, url}}",
        typical_latency_ms=100,
        used_by_agents=["RegulationEngine"],
        router_file="botproject/routers/legal.py",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# EAZR CREDIT WAITLIST  (3)
# ═══════════════════════════════════════════════════════════════════════════════

EAZR_CREDIT_ENDPOINTS: List[ExistingEndpoint] = [

    ExistingEndpoint(
        name="join_eazr_credit_waitlist",
        category=EndpointCategory.IPF_SVF,
        method="POST", path="/api/eazr-credit/waitlist/join",
        auth_required=True, auth_type="jwt",
        params=[EndpointParam("user_id", "str", True, "User ID", location="body")],
        response_description="{success, message, data{waitlistId, position, estimatedAccess}}",
        typical_latency_ms=400,
        router_file="botproject/routers/eazr_credit.py",
        notes="409 if already on waitlist.",
    ),
    ExistingEndpoint(
        name="get_eazr_credit_status",
        category=EndpointCategory.IPF_SVF,
        method="GET", path="/api/eazr-credit/waitlist/status/{user_id}",
        auth_required=True, auth_type="jwt",
        params=[EndpointParam("user_id", "str", True, "User ID", location="path")],
        response_description="{success, data{position, status, estimatedAccess}}",
        typical_latency_ms=300,
        router_file="botproject/routers/eazr_credit.py",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# CONTACT SUPPORT  (2 public)
# ═══════════════════════════════════════════════════════════════════════════════

SUPPORT_ENDPOINTS: List[ExistingEndpoint] = [

    ExistingEndpoint(
        name="get_contact_support",
        category=EndpointCategory.ADMIN,
        method="GET", path="/support/contact",
        auth_required=False, auth_type="none",
        response_description="{success, data{email, phone, whatsapp, liveChat, socialMedia, officeAddress}}",
        typical_latency_ms=150,
        used_by_agents=["GrievanceNavigator", "ClaimsGuide"],
        router_file="botproject/routers/contact_support.py",
        notes="Public. Returns latest contact info from MongoDB.",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# MASTER ENDPOINT LIST
# ═══════════════════════════════════════════════════════════════════════════════

ENDPOINTS: List[ExistingEndpoint] = (
    AUTH_ENDPOINTS
    + POLICY_EXTRACTION_ENDPOINTS
    + USER_POLICY_ENDPOINTS
    + POLICY_LOCKER_ENDPOINTS
    + CHAT_ENDPOINTS
    + CLAIM_ENDPOINTS
    + DASHBOARD_ENDPOINTS
    + FAMILY_ENDPOINTS
    + BILL_AUDIT_ENDPOINTS
    + HBF_ENDPOINTS
    + CARD_ENDPOINTS
    + USER_ENDPOINTS
    + NOTIFICATION_ENDPOINTS
    + HEALTH_ENDPOINTS
    + REWARDS_ENDPOINTS
    + LEGAL_ENDPOINTS
    + EAZR_CREDIT_ENDPOINTS
    + SUPPORT_ENDPOINTS
)


# ═══════════════════════════════════════════════════════════════════════════════
# EXISTING SERVICES (importable directly if co-located)
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class ExistingService:
    name: str
    file: str
    class_name: str
    key_methods: List[str]
    description: str
    has_http_endpoint: bool
    llm_provider: str = "none"   # "openai" | "deepseek" | "none"
    notes: str = ""


SERVICES: List[ExistingService] = [

    ExistingService(
        name="PolicyExtractionPipeline",
        file="botproject/policy_analysis/",
        class_name="(pipeline, not a single class)",
        key_methods=[
            "extract_policy_data(pdf_bytes, policy_type) -> Dict",
            "classify_policy(extraction) -> {category, subcategory, confidence}",
            "compute_universal_scores(v2_raw, category, insurer) -> {vfm, coverage_strength, claim_readiness}",
            "classify_zones(v2_raw, category, insurer) -> List[{feature, zone, label}]",
            "check_irdai_compliance(v2_raw, category) -> List[{mandateId, passed, status}]",
        ],
        description=(
            "7-stage pipeline: extract→classify→score→zone→validate→comply→report. "
            "DeepSeek for extraction, rule-based for scoring/zoning/compliance."
        ),
        has_http_endpoint=True,
        llm_provider="deepseek",
        notes="Supports health/life/motor/travel/PA. Extraction uses type-specific prompts.",
    ),

    ExistingService(
        name="ProtectionScoreCalculator",
        file="botproject/services/protection_score_calculator.py",
        class_name="(standalone functions)",
        key_methods=[
            "calculate_protection_score(policy_type, gaps, extracted_data, category_data) -> Tuple[int, str]",
            "calculate_health_score_v10(data) -> Tuple[int, str]",
            "calculate_motor_score(data) -> Tuple[int, str]",
            "calculate_life_score(data) -> Tuple[int, str]",
        ],
        description="Pure algorithmic protection score (0-100). No LLM. Verdict: Excellent/Strong/Adequate/Moderate/Needs Attention.",
        has_http_endpoint=True,
        llm_provider="none",
        notes="S1-S4 sub-scores for health: Emergency Readiness, Critical Illness, Family Protection, Coverage Stability.",
    ),

    ExistingService(
        name="InsuranceProviderInfoService",
        file="botproject/services/insurance_provider_info.py",
        class_name="(static dict PROVIDER_DATA)",
        key_methods=[
            "get_provider_info(insurer_name: str) -> Dict",
            "get_claim_settlement_ratio(insurer_name: str) -> float",
            "get_provider_contacts(insurer_name: str) -> Dict",
        ],
        description="Static database of 30+ Indian insurers: CSR, contact info, IRDAI reg, network size, specialties.",
        has_http_endpoint=False,
        llm_provider="none",
        notes=(
            "KEY for Hibiscus. Covers: ACKO, Niva Bupa, ICICI Lombard, HDFC ERGO, Bajaj, "
            "Aditya Birla, SBI, Star Health, Apollo, National, United India, Oriental, "
            "ICICI Prudential, HDFC Life, Max Life, Kotak, etc. "
            "NO HTTP endpoint — needs one added for Hibiscus HTTP access."
        ),
    ),

    ExistingService(
        name="UINWebEnrichmentService",
        file="botproject/services/uin_web_enrichment_service.py",
        class_name="UINWebEnrichmentService",
        key_methods=[
            "enrich_from_uin(uin: str, policy_type: str) -> Dict",
            "parse_uin(uin: str) -> {insurer_code, product_code}",
            "_query_deepseek(uin, policy_type) -> Dict",
            "_search_jina(uin) -> Dict",
        ],
        description="Given a UIN, enriches policy data via DeepSeek LLM + Jina web search. 24-hour cache.",
        has_http_endpoint=False,
        llm_provider="deepseek",
        notes="NO HTTP endpoint — needs one added. Critical for improving thin-document extractions.",
    ),

    ExistingService(
        name="IndianMarketDataService",
        file="botproject/services/indian_market_data_service.py",
        class_name="IndianMarketDataService",
        key_methods=[
            "get_city_healthcare_costs(city: str) -> Dict",
            "get_recommended_sum_insured(age, family_size, city) -> int",
            "get_medical_inflation_rate() -> float",
            "get_motor_insurance_market_data() -> Dict",
            "get_metal_depreciation_rate(year, metal_type) -> float",
            "get_pa_cover_amount() -> Dict",
        ],
        description="Fetches live Indian market data via DeepSeek LLM. 24-hour cache per data type.",
        has_http_endpoint=False,
        llm_provider="deepseek",
        notes=(
            "NO HTTP endpoint. Used internally by report generators. "
            "Hibiscus agents need this for benchmarking and recommendations."
        ),
    ),

    ExistingService(
        name="ReportGenerators",
        file="botproject/services/*_insurance_report_generator.py",
        class_name="Health/Motor/Life/Travel/PAInsuranceReportGenerator",
        key_methods=[
            "generate_report(extracted_data, scores, gaps, user_data) -> bytes (PDF)",
            "generate_health_report(data) -> bytes",
            "generate_motor_report(data) -> bytes",
            "generate_life_report(data) -> bytes",
        ],
        description="Type-specific 8-page PDF reports using ReportLab. Branded EAZR design.",
        has_http_endpoint=True,
        llm_provider="none",
        notes="Report URL returned from /api/policy/upload. S3 upload for persistence.",
    ),

    ExistingService(
        name="AuthService",
        file="botproject/services/auth_service.py",
        class_name="AuthService",
        key_methods=[
            "send_otp_to_phone(phone) -> Dict",
            "verify_otp_and_create_sessions(phone, otp, metadata) -> Dict",
            "verify_oauth_and_create_sessions(provider, idToken, metadata) -> Dict",
            "validate_and_regenerate_session(session_id) -> Dict",
        ],
        description="OTP + OAuth authentication. Calls eazr.in OTP API. Creates MongoDB sessions.",
        has_http_endpoint=True,
        llm_provider="none",
    ),

    ExistingService(
        name="PolicyLockerService",
        file="botproject/services/policy_locker_service.py",
        class_name="PolicyLockerService",
        key_methods=[
            "get_user_policies(user_id, filters) -> List[Dict]",
            "get_policy_detail(policy_id, user_id) -> Dict",
            "add_policy(user_id, policy_data) -> str",
            "delete_policy(policy_id, user_id) -> bool",
            "get_family_members(user_id) -> List[Dict]",
            "initiate_claim(policy_id, claim_data) -> Dict",
        ],
        description="Full policy locker CRUD + family member management + claims.",
        has_http_endpoint=True,
        llm_provider="none",
    ),

    ExistingService(
        name="BillAuditService",
        file="botproject/services/bill_audit_service.py",
        class_name="BillAuditService",
        key_methods=[
            "process_bill_upload(files, user_id, policy_id) -> Dict",
            "get_audit_result(audit_id, user_id) -> Dict",
            "get_audit_history(user_id, limit, offset) -> Dict",
            "generate_report(audit_id) -> str (URL)",
            "generate_dispute_letter(audit_id, include_pdf) -> Dict",
        ],
        description="Hospital bill analysis: extraction, discrepancy detection, dispute letter generation.",
        has_http_endpoint=True,
        llm_provider="openai",
    ),

    ExistingService(
        name="CardService",
        file="botproject/services/card_service.py",
        class_name="CardService",
        key_methods=[
            "get_credit_cards(skip, limit) -> List",
            "search_credit_cards(query) -> List",
            "get_card_benefits(card_id) -> Dict",
            "bin_lookup(bin_number) -> Dict",
            "get_user_cards(user_id) -> List",
        ],
        description="Credit/debit card database with insurance benefits. 50+ bank normalization.",
        has_http_endpoint=True,
        llm_provider="none",
    ),

    ExistingService(
        name="NotificationService",
        file="botproject/services/notification_service.py",
        class_name="NotificationService",
        key_methods=[
            "register_device_token(user_id, fcm_token, device_type) -> Tuple",
            "send_notification(user_id, title, body, data) -> bool",
            "send_bulk_notification(user_ids, notification) -> Dict",
            "get_notification_history(user_id, limit) -> List",
        ],
        description="Firebase FCM push notifications with history tracking.",
        has_http_endpoint=True,
        llm_provider="none",
    ),

    ExistingService(
        name="ChatMemoryManager",
        file="botproject/ai_chat_components/chat_memory.py",
        class_name="ChatMemoryManager",
        key_methods=[
            "add_message(session_id, role, content, intent, metadata) -> bool",
            "get_messages(session_id, limit) -> List[ChatMessage]",
            "get_session_summary(session_id) -> ConversationSummary",
            "update_user_context(session_id, user_id, context) -> bool",
        ],
        description="Hybrid memory: MongoDB primary, Redis cache, in-memory fallback. 14-day TTL.",
        has_http_endpoint=False,
        llm_provider="none",
        notes="Hibiscus will use its own LangGraph memory. This is for legacy chat.",
    ),

    ExistingService(
        name="LLMManager",
        file="botproject/ai_chat_components/llm_config.py",
        class_name="LLMManager",
        key_methods=[
            "get_llm(use_case: str) -> ChatOpenAI",
            "_try_primary() -> ChatOpenAI",
            "_try_fallback() -> ChatOpenAI",
        ],
        description="Primary: gpt-4o-mini. Fallback: GLM-4.5-Air. Auto-switches on failure.",
        has_http_endpoint=False,
        llm_provider="openai",
        notes="Max 2 retries before fallback. Hibiscus will manage its own LLM clients.",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# DATABASE MODELS
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class ExistingModel:
    name: str
    file: str
    database: str                  # "mongodb" | "postgresql" | "redis" | "faiss"
    collection_or_table: str
    key_fields: List[str]
    description: str


MODELS: List[ExistingModel] = [

    # ── MongoDB collections ──────────────────────────────────────────────────
    ExistingModel(
        name="User", file="botproject/models/user.py",
        database="mongodb", collection_or_table="users",
        key_fields=["userId", "phone", "name", "email", "dob", "gender", "chatSessionHistory", "createdAt"],
        description="User profile, demographics, chat session references.",
    ),
    ExistingModel(
        name="ChatSession", file="botproject/ai_chat_components/chat_memory.py",
        database="mongodb", collection_or_table="sessions",
        key_fields=["chatSessionId", "userId", "title", "messages", "isArchived", "deleted", "createdAt"],
        description="Chat session with full message history. Soft delete supported.",
    ),
    ExistingModel(
        name="PolicyAnalysis", file="botproject/routers/policy_upload.py",
        database="mongodb", collection_or_table="policy_analyses_collection",
        key_fields=["policyId", "userId", "policyType", "extraction_v2", "scores", "zones", "verdict", "compliance", "reportUrl", "createdAt"],
        description="Complete policy analysis result from the 7-stage pipeline.",
    ),
    ExistingModel(
        name="ClaimGuidance", file="botproject/services/policy_service.py",
        database="mongodb", collection_or_table="claim_guidance_collection",
        key_fields=["userId", "query", "insuranceType", "response", "action", "suggestions", "createdAt"],
        description="Stored claim guidance queries and LLM responses.",
    ),
    ExistingModel(
        name="DeviceToken", file="botproject/models/notification.py",
        database="mongodb", collection_or_table="device_tokens",
        key_fields=["userId", "fcmToken", "deviceType", "deviceName", "appVersion", "isActive", "createdAt"],
        description="Firebase FCM push notification tokens.",
    ),
    ExistingModel(
        name="NotificationLog", file="botproject/models/notification.py",
        database="mongodb", collection_or_table="notification_logs",
        key_fields=["userId", "title", "body", "type", "read", "sentAt"],
        description="Notification history with read status.",
    ),
    ExistingModel(
        name="BillAudit", file="botproject/models/bill_audit.py",
        database="mongodb", collection_or_table="bill_audits",
        key_fields=["auditId", "userId", "policyId", "status", "discrepancies", "savings", "billData", "reportUrl"],
        description="Hospital bill audit results with discrepancy detection.",
    ),
    ExistingModel(
        name="PolicyLocker", file="botproject/models/policy_locker.py",
        database="mongodb", collection_or_table="policy_locker_collection",
        key_fields=["policyId", "userId", "policyNumber", "provider", "category", "status", "premium", "coverageAmount", "expiryDate"],
        description="User policy vault — confirmed and analyzed policies.",
    ),
    ExistingModel(
        name="FamilyMember", file="botproject/models/policy_locker.py",
        database="mongodb", collection_or_table="family_members_collection",
        key_fields=["memberId", "userId", "name", "relationship", "dob", "gender", "policies"],
        description="Family member profiles linked to user.",
    ),
    ExistingModel(
        name="EazrCreditWaitlist", file="botproject/models/eazr_credit.py",
        database="mongodb", collection_or_table="eazr_credit_waitlist",
        key_fields=["userId", "waitlistId", "position", "status", "joinedAt"],
        description="Eazr Credit product waitlist.",
    ),
    ExistingModel(
        name="Card", file="botproject/models/card.py",
        database="mongodb", collection_or_table="credit_card / debit_card",
        key_fields=["cardId", "name", "bank", "scheme", "benefits", "insuranceCover"],
        description="Credit/debit card database with insurance benefits. In 'Cards' DB (separate from insurance_analysis_db).",
    ),
    ExistingModel(
        name="ContactSupport", file="botproject/models/contact_support.py",
        database="mongodb", collection_or_table="contact_support_collection",
        key_fields=["email", "phone", "whatsapp", "socialMedia", "officeAddress", "updatedAt"],
        description="EAZR support contact configuration.",
    ),

    # ── PostgreSQL ───────────────────────────────────────────────────────────
    ExistingModel(
        name="InsuranceProduct", file="botproject/init/04_product_tables.sql",
        database="postgresql", collection_or_table="insurance_products",
        key_fields=["product_id", "uin", "company_id", "product_name", "category_id", "subcategory_id"],
        description="IRDAI-approved insurance products with UIN. Source of truth for product data.",
    ),
    ExistingModel(
        name="InsuranceCompany", file="botproject/init/02_company_tables.sql",
        database="postgresql", collection_or_table="insurance_companies",
        key_fields=["company_id", "company_name", "irdai_registration", "type"],
        description="Insurance companies registered with IRDAI.",
    ),
    ExistingModel(
        name="InsuranceCategory", file="botproject/init/03_category_tables.sql",
        database="postgresql", collection_or_table="insurance_categories / subcategories",
        key_fields=["category_id", "category_name", "subcategory_id", "subcategory_name"],
        description="Product category and subcategory taxonomy.",
    ),

    # ── Redis ────────────────────────────────────────────────────────────────
    ExistingModel(
        name="SessionCache", file="botproject/session_security/session_manager.py",
        database="redis", collection_or_table="session:{session_id}",
        key_fields=["user_id", "phone", "access_token", "expires_at"],
        description="Session validation cache. TTL 14 days.",
    ),
    ExistingModel(
        name="RateLimitCounters", file="botproject/core/rate_limiter.py",
        database="redis", collection_or_table="ratelimit:{identifier}:{endpoint}",
        key_fields=["count", "window_start"],
        description="Sliding window rate limit counters per IP/user per endpoint.",
    ),

    # ── FAISS ────────────────────────────────────────────────────────────────
    ExistingModel(
        name="FAISSVectorIndex", file="botproject/ai_chat_components/vectore_store.py",
        database="faiss", collection_or_table="faiss_index/",
        key_fields=["embedding_vector", "document_chunk", "source"],
        description="OpenAI embedding vectors for RAG chain. Loaded at startup.",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# LLM INTEGRATION POINTS
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class ExistingLLMUsage:
    file: str
    provider: str          # "openai" | "deepseek" | "glm" | "langchain"
    model: str
    purpose: str
    temperature: float = 0.7
    max_tokens: int = 1024
    prompt_file: Optional[str] = None


LLM_USAGES: List[ExistingLLMUsage] = [

    ExistingLLMUsage(
        file="botproject/ai_chat_components/llm_config.py",
        provider="openai", model="gpt-4o-mini",
        purpose="Primary chat LLM: intent detection, casual responses, claim guidance",
        temperature=0.7, max_tokens=1024,
    ),
    ExistingLLMUsage(
        file="botproject/ai_chat_components/llm_config.py",
        provider="glm", model="GLM-4.5-Air",
        purpose="Fallback LLM when OpenAI unavailable",
        temperature=0.7, max_tokens=500,
    ),
    ExistingLLMUsage(
        file="botproject/policy_analysis/extraction/llm_client.py",
        provider="deepseek", model="deepseek-chat",
        purpose="Policy data extraction from PDF text",
        temperature=0.0, max_tokens=4000,
        prompt_file="botproject/policy_analysis/extraction/prompts/{type}_prompt.py",
    ),
    ExistingLLMUsage(
        file="botproject/policy_analysis/extraction/llm_client.py",
        provider="deepseek", model="deepseek-chat",
        purpose="Gap analysis on extracted policy data",
        temperature=0.2, max_tokens=2500,
        prompt_file="botproject/policy_analysis/extraction/gap_analysis_prompts.py",
    ),
    ExistingLLMUsage(
        file="botproject/policy_analysis/extraction/llm_client.py",
        provider="deepseek", model="deepseek-chat",
        purpose="Insights generation on analyzed policy",
        temperature=0.3, max_tokens=2000,
        prompt_file="botproject/policy_analysis/extraction/insights_prompts.py",
    ),
    ExistingLLMUsage(
        file="botproject/services/indian_market_data_service.py",
        provider="deepseek", model="deepseek-chat",
        purpose="Live Indian insurance market data queries (costs, rates, inflation)",
        temperature=0.1, max_tokens=1000,
    ),
    ExistingLLMUsage(
        file="botproject/services/uin_web_enrichment_service.py",
        provider="deepseek", model="deepseek-chat",
        purpose="UIN-based policy T&C enrichment from IRDAI product knowledge",
        temperature=0.1, max_tokens=3000,
    ),
    ExistingLLMUsage(
        file="botproject/core/config.py",
        provider="langchain", model="OpenAI Embeddings (text-embedding-3-small default)",
        purpose="RAG document embeddings, stored in FAISS",
        temperature=0.0, max_tokens=0,
    ),
    ExistingLLMUsage(
        file="botproject/financial_services/bill_audit_analyzer.py",
        provider="openai", model="gpt-4o-mini",
        purpose="Hospital bill extraction + discrepancy detection",
        temperature=0.1, max_tokens=4000,
    ),
    ExistingLLMUsage(
        file="botproject/ai_chat_components/langgraph_chatbot.py",
        provider="langchain", model="gpt-4o-mini (via LangGraph)",
        purpose="Multi-turn stateful conversation management",
        temperature=0.7, max_tokens=1024,
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# EXTERNAL INTEGRATIONS
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class ExternalIntegration:
    name: str
    base_url: str
    purpose: str
    auth_method: str
    used_in_file: str
    notes: str = ""


EXTERNAL_INTEGRATIONS: List[ExternalIntegration] = [

    ExternalIntegration(
        name="EAZR OTP API",
        base_url="https://api.prod.eazr.in",
        purpose="Send and verify OTPs for phone authentication",
        auth_method="API key in headers",
        used_in_file="botproject/services/auth_service.py",
        notes="External eazr.in backend. Primary auth method.",
    ),
    ExternalIntegration(
        name="OpenAI API",
        base_url="https://api.openai.com/v1",
        purpose="gpt-4o-mini for chat, text-embedding for RAG",
        auth_method="Bearer API key (OPENAI_API_KEY env)",
        used_in_file="botproject/ai_chat_components/llm_config.py, core/config.py",
    ),
    ExternalIntegration(
        name="DeepSeek API",
        base_url="https://api.deepseek.com",
        purpose="Policy extraction, gap analysis, market data, UIN enrichment",
        auth_method="Bearer API key (DEEPSEEK_API_KEY env)",
        used_in_file="botproject/policy_analysis/extraction/llm_client.py, services/indian_market_data_service.py",
        notes="OpenAI-compatible API. Temperature 0.0-0.3 for deterministic outputs.",
    ),
    ExternalIntegration(
        name="GLM / Z.ai API",
        base_url="https://api.z.ai/api/paas/v4/",
        purpose="Fallback LLM when OpenAI unavailable",
        auth_method="Bearer API key",
        used_in_file="botproject/ai_chat_components/llm_config.py",
        notes="GLM-4.5-Air model. Lower quality than primary but reliable fallback.",
    ),
    ExternalIntegration(
        name="Firebase Admin SDK",
        base_url="https://fcm.googleapis.com",
        purpose="Push notifications via FCM to iOS/Android devices",
        auth_method="Service account JSON (eazrapp-firebase-adminsdk.json)",
        used_in_file="botproject/database_storage/firebase_config.py, services/notification_service.py",
        notes="Credentials file excluded from git. Required for notifications.",
    ),
    ExternalIntegration(
        name="AWS S3",
        base_url="https://s3.amazonaws.com",
        purpose="Store original policy PDFs and generated report PDFs",
        auth_method="AWS Access Key + Secret Key (env vars)",
        used_in_file="botproject/database_storage/s3_bucket.py",
        notes="Bucket: raceabove-dev. Path: /original_docs/{user_id}/{timestamp}_{filename}",
    ),
    ExternalIntegration(
        name="Jina Web Search",
        base_url="https://r.jina.ai",
        purpose="Web search for UIN enrichment when DeepSeek knowledge is thin",
        auth_method="API key",
        used_in_file="botproject/services/uin_web_enrichment_service.py",
        notes="Fallback after DeepSeek LLM query for policy T&C.",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# AGENT → ENDPOINT MAPPING
# ═══════════════════════════════════════════════════════════════════════════════

AGENT_TOOL_MAP: Dict[str, List[str]] = {

    "PolicyAnalyzer": [
        "upload_and_analyze_policy",      # Core: PDF → full analysis
        "get_policy_detail",              # Deep dive on specific policy
        "get_user_policies",              # Portfolio view
        "get_protection_score",           # Current score
        "get_claim_guidance",             # Claim-related queries
        "analyze_locker_policy",          # Re-analyze policy in locker
        "get_card_benefits",              # Embedded card insurance check
        "get_user_profile",               # Age/demographics context
        "health_check",                   # Service availability
    ],

    "SurrenderCalculator": [
        "get_policy_detail",              # Policy terms + premium data
        "get_user_policies",              # Life policies in portfolio
        "get_user_profile",               # Age/tenure context
        # MISSING: surrender_value_calculator endpoint
    ],

    "Recommender": [
        "get_user_policies",              # Current portfolio
        "get_portfolio_breakdown",        # Category coverage
        "get_family_coverage",            # Family members + coverage
        "get_dashboard_insights",         # Existing insights
        "get_renewals",                   # Upcoming renewals
        "search_credit_cards",            # Card-embedded insurance
        "get_card_benefits",              # Card benefit details
        "get_user_cards",                 # User's linked cards
        "get_user_profile",               # Demographics
        "get_rewards_progress",           # Gamification context
        "check_reward_eligibility",       # Free PA policy eligibility
    ],

    "ClaimsGuide": [
        "get_claim_guidance",             # LLM-powered claim steps
        "get_policy_detail",              # Policy terms
        "upload_bill",                    # Bill audit upload
        "get_bill_audit_result",          # Audit findings
        "generate_bill_audit_report",     # PDF report
        "generate_dispute_letter",        # Dispute template
        "check_hbf_eligibility",          # Financing option
        "get_hbf_offers",                 # Financing offers
        "get_emergency_services",         # Emergency contacts
        "get_claim_details",              # Claim status
        "get_contact_support",            # EAZR support contacts
    ],

    "Calculator": [
        "get_protection_score",           # Score with breakdown
        "refresh_protection_score",       # Recalculate after income update
        "get_portfolio_breakdown",        # Coverage by category
        "get_dashboard_insights",         # Recommendations
        "get_user_policies",              # Policy data for calculations
    ],

    "Researcher": [
        "health_check",                   # Service probe
        "get_privacy_policy",             # EAZR policy docs
        "get_terms_and_conditions",       # EAZR T&Cs
        # Researcher primarily uses RAG/web search — minimal existing API
    ],

    "RegulationEngine": [
        "get_policy_detail",              # compliance[] field from analysis
        "get_privacy_policy",             # EAZR compliance docs
        "get_terms_and_conditions",       # EAZR T&Cs
        # IRDAI compliance is run during extraction; results in policy_detail
    ],

    "RiskDetector": [
        "get_policy_detail",              # Full policy + validation + zones
        "get_user_policies",              # Portfolio-wide risks
        "get_protection_score",           # Overall risk score
        "get_family_coverage",            # Family coverage gaps
        "analyze_locker_policy",          # Deep re-analysis
    ],

    "Educator": [
        "get_policy_detail",              # Policy terms to explain
        "get_user_policies",              # User's context
        "get_contact_support",            # Support info
        # Educator primarily uses RAG over IRDAI docs
    ],

    "PortfolioOptimizer": [
        "get_user_policies",              # Full portfolio
        "get_protection_score",           # Current score
        "get_portfolio_breakdown",        # Category breakdown
        "get_family_coverage",            # Family policies
        "get_dashboard_insights",         # Existing recommendations
        "get_renewals",                   # Upcoming renewals
        "get_self_policies",              # Self policies
        "get_family_policies",            # Family policies (locker)
        "get_locker_summary",             # Portfolio stats
        "refresh_protection_score",       # After changes
        "get_user_cards",                 # Card-embedded insurance
        "get_user_profile",               # Income/demographics
    ],

    "TaxAdvisor": [
        "get_user_policies",              # 80C/80D eligible policies
        "get_policy_detail",              # Premium amounts, terms
        "get_family_coverage",            # Dependent family coverage
        "get_user_profile",               # Age, income bracket
        # MISSING: dedicated tax_benefit_calculator endpoint
    ],

    "GrievanceNavigator": [
        "get_claim_guidance",             # Claim step guidance
        "get_contact_support",            # EAZR support contacts
        "generate_dispute_letter",        # Dispute letter for insurer
        "get_emergency_services",         # Emergency numbers
        # Primarily uses RAG over IRDAI grievance docs
    ],
}


# ═══════════════════════════════════════════════════════════════════════════════
# MISSING ENDPOINTS — Gaps Hibiscus needs filled
# ═══════════════════════════════════════════════════════════════════════════════

MISSING_ENDPOINTS: List[Dict[str, str]] = [

    {
        "name": "get_insurer_profile",
        "needed_by": "PolicyAnalyzer, Recommender, RiskDetector, Educator",
        "suggested_path": "/api/v1/insurer/{insurer_name}/profile",
        "data_source": "botproject/services/insurance_provider_info.py (PROVIDER_DATA dict — static, no endpoint)",
        "priority": "HIGH",
        "effort": "LOW — just expose existing static dict via GET endpoint",
        "notes": "CSR ratio, network size, IRDAI reg, contact info, specialties. 30+ insurers covered.",
    },
    {
        "name": "enrich_from_uin",
        "needed_by": "PolicyAnalyzer, RegulationEngine",
        "suggested_path": "/api/v1/policy/enrich-uin",
        "data_source": "botproject/services/uin_web_enrichment_service.py (exists, no endpoint)",
        "priority": "HIGH",
        "effort": "LOW — expose existing service via POST endpoint",
        "notes": "DeepSeek + Jina search. 24-hour cache. Critical for thin-document policies.",
    },
    {
        "name": "get_indian_market_data",
        "needed_by": "Calculator, Recommender, PortfolioOptimizer",
        "suggested_path": "/api/v1/market-data/{data_type}",
        "data_source": "botproject/services/indian_market_data_service.py (exists, no endpoint)",
        "priority": "MEDIUM",
        "effort": "LOW — expose existing service",
        "notes": "Healthcare costs, SI recommendations, inflation, motor rates. DeepSeek-powered.",
    },
    {
        "name": "calculate_surrender_value",
        "needed_by": "SurrenderCalculator",
        "suggested_path": "/api/v1/policy/{policy_id}/surrender-value",
        "data_source": "No implementation exists",
        "priority": "HIGH",
        "effort": "HIGH — needs new service + actuarial logic",
        "notes": "Must handle: traditional endowment, ULIP, term. IRDAI surrender value regulations apply.",
    },
    {
        "name": "calculate_tax_benefits",
        "needed_by": "TaxAdvisor",
        "suggested_path": "/api/v1/user/{user_id}/tax-benefits",
        "data_source": "No implementation exists",
        "priority": "MEDIUM",
        "effort": "MEDIUM — needs 80C/80D rules engine",
        "notes": "80C (life premiums), 80D (health premiums + preventive health). Income bracket aware.",
    },
    {
        "name": "search_products_by_criteria",
        "needed_by": "Recommender",
        "suggested_path": "/api/v1/products/search",
        "data_source": "PostgreSQL insurance_india DB (products exist, no search endpoint)",
        "priority": "HIGH",
        "effort": "MEDIUM — needs PostgreSQL query layer",
        "notes": "Filter by: category, max_premium, min_coverage, insurer, uin. Required for product recommendations.",
    },
    {
        "name": "get_irdai_grievance_info",
        "needed_by": "GrievanceNavigator",
        "suggested_path": "/api/v1/grievance/process",
        "data_source": "No implementation — would need RAG over IRDAI docs",
        "priority": "MEDIUM",
        "effort": "MEDIUM — RAG pipeline over IRDAI grievance PDFs",
        "notes": "IGMS portal info, timelines, escalation paths.",
    },
    {
        "name": "compare_policies",
        "needed_by": "PolicyAnalyzer, Recommender",
        "suggested_path": "/api/v1/policies/compare",
        "data_source": "botproject/services/policy_service.py — compare_policies() method exists",
        "priority": "MEDIUM",
        "effort": "LOW — endpoint partially exists, needs standardization",
        "notes": "Side-by-side comparison of 2-4 policies. Returns lowest_premium, highest_coverage, best_value.",
    },
    {
        "name": "get_claim_status_history",
        "needed_by": "ClaimsGuide",
        "suggested_path": "/api/v1/claims/{claim_id}/timeline",
        "data_source": "claims_collection exists in MongoDB, no timeline endpoint",
        "priority": "LOW",
        "effort": "LOW",
        "notes": "Chronological claim status updates with timestamps.",
    },
]


# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION DISCOVERED
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class ExistingConfig:
    api_base_url: str = ""
    api_version: str = ""
    auth_method: str = ""
    databases: Dict[str, str] = field(default_factory=dict)
    llm_providers: Dict[str, str] = field(default_factory=dict)
    file_storage: str = ""
    rate_limiting: str = ""
    cors_policy: str = ""


EXISTING_CONFIG = ExistingConfig(
    api_base_url="http://localhost:8000",       # Docker: http://eazr-app:8000
    api_version="v1 (mixed — some /api/v1/, some /api/, some bare)",
    auth_method="Session ID + JWT Bearer (HS256, 14-day expiry). Admin: username/password.",
    databases={
        "mongodb":    "mongodb://eazr-mongo:27017/insurance_analysis_db (Docker) | mongodb://localhost:27017/ (local)",
        "postgresql": "postgresql://eazr:eazr_secure_2024@eazr-postgres:5432/insurance_india",
        "redis":      "redis://eazr-redis:6379",
        "faiss":      "local file: botproject/faiss_index/ (loaded at startup)",
        "s3":         "AWS S3 bucket: raceabove-dev",
    },
    llm_providers={
        "openai":   "gpt-4o-mini (chat primary) + text-embedding-3-small (RAG)",
        "deepseek": "deepseek-chat (extraction, analysis, market data)",
        "glm":      "GLM-4.5-Air via api.z.ai (OpenAI fallback)",
    },
    file_storage="AWS S3 (raceabove-dev bucket) + local /app/uploads/",
    rate_limiting="Redis sliding window. Limits: 3-60/min per endpoint per IP/user.",
    cors_policy="Dynamic origin validation. Wildcard patterns supported.",
)


# ═══════════════════════════════════════════════════════════════════════════════
# DISCOVERY SUMMARY
# ═══════════════════════════════════════════════════════════════════════════════

DISCOVERY_SUMMARY = {
    "total_endpoints":          len(ENDPOINTS),
    "total_services":           len(SERVICES),
    "total_models":             len(MODELS),
    "total_llm_usages":         len(LLM_USAGES),
    "total_external_integrations": len(EXTERNAL_INTEGRATIONS),
    "missing_endpoints":        len(MISSING_ENDPOINTS),
    "endpoint_breakdown": {
        "auth":                 len(AUTH_ENDPOINTS),
        "policy_extraction":    len(POLICY_EXTRACTION_ENDPOINTS),
        "user_policies":        len(USER_POLICY_ENDPOINTS),
        "policy_locker":        len(POLICY_LOCKER_ENDPOINTS),
        "chat":                 len(CHAT_ENDPOINTS),
        "claims":               len(CLAIM_ENDPOINTS),
        "dashboard_portfolio":  len(DASHBOARD_ENDPOINTS),
        "family":               len(FAMILY_ENDPOINTS),
        "bill_audit":           len(BILL_AUDIT_ENDPOINTS),
        "hbf_financing":        len(HBF_ENDPOINTS),
        "cards":                len(CARD_ENDPOINTS),
        "user":                 len(USER_ENDPOINTS),
        "notifications":        len(NOTIFICATION_ENDPOINTS),
        "health":               len(HEALTH_ENDPOINTS),
        "rewards":              len(REWARDS_ENDPOINTS),
        "legal":                len(LEGAL_ENDPOINTS),
        "eazr_credit":          len(EAZR_CREDIT_ENDPOINTS),
        "support":              len(SUPPORT_ENDPOINTS),
    },
    "agent_readiness_pct": {
        # % of tools each agent needs that already have HTTP endpoints
        "PolicyAnalyzer":       90,   # Missing: insurer profile, UIN enrich
        "SurrenderCalculator":  30,   # Missing: surrender value calculator (core feature)
        "Recommender":          75,   # Missing: product search endpoint
        "ClaimsGuide":          85,   # Missing: claim timeline
        "Calculator":           90,   # Missing: market data endpoint (service exists)
        "Researcher":           70,   # Needs RAG pipeline, minimal existing API
        "RegulationEngine":     70,   # Compliance in policy_detail; missing IRDAI docs RAG
        "RiskDetector":         90,   # Good coverage
        "Educator":             60,   # Needs IRDAI docs RAG pipeline
        "PortfolioOptimizer":   95,   # Excellent coverage
        "TaxAdvisor":           60,   # Missing: tax benefit calculator
        "GrievanceNavigator":   65,   # Missing: IRDAI grievance RAG, dispute letter exists
    },
    "top_risks": [
        "SurrenderCalculator has no backend implementation — needs actuarial logic build",
        "InsuranceProviderInfoService is static dict — no HTTP endpoint; needs adding",
        "MarketDataService and UINEnrichmentService have no HTTP endpoints; services exist",
        "PostgreSQL product search has no endpoint — Recommender blocked without it",
        "Policy path inconsistency: /api/v1/, /api/, and bare paths mixed across routers",
        "Auth: session_id and JWT co-exist but aren't unified — Hibiscus must handle both",
        "No compare_policies HTTP endpoint despite service method existing",
        "FAISS index is local — if eazr-app restarts without volume it's empty",
    ],
    "recommended_approach": (
        "Call existing endpoints via HTTP from Hibiscus agents. "
        "Do NOT import botproject services directly — keeps services independently deployable. "
        "Add 3 missing low-effort endpoints first: insurer_profile, enrich_uin, market_data. "
        "Build surrender_value and tax_benefit as new Hibiscus-native services. "
        "Use WebSocket /ws/chat for streaming Hibiscus responses to existing Flutter clients."
    ),
}
