"""
Insurer Seed Data
==================
50+ Indian insurers with accurate IRDAI public data.
Sources: IRDAI Annual Report 2022-23, insurer disclosures.

All CSR/ICR figures are annual averages from IRDAI published data.
Run via: python -m hibiscus.knowledge.graph.seed
Copyright (c) 2026 EAZR Digipayments Pvt Ltd. All rights reserved.
"""
from typing import Any, Dict, List

from hibiscus.knowledge.graph.client import Neo4jClient
from hibiscus.observability.logger import get_logger

logger = get_logger("hibiscus.kg.seed.insurers")

# ── Data ──────────────────────────────────────────────────────────────────────
# Field reference:
#   name                     : str   — unique insurer name
#   type                     : str   — "public_life" | "private_life" | "standalone_health"
#                                       | "general" | "private_general"
#   csr                      : float — Claim Settlement Ratio (%) for life; for health/general
#                                       this is claims-paid ratio
#   solvency_ratio           : float — Solvency ratio (regulatory min = 1.50)
#   complaint_ratio          : float — complaints per 10,000 policies
#   market_share             : float — % of industry new business premium
#   icr                      : float — Incurred Claims Ratio (%) — health/general specific
#   network_hospitals        : int   — cashless network hospital count
#   claim_settlement_time_avg: int   — average days to settle a claim
#   digital_score            : int   — EAZR proprietary digital experience score (1-10)

INSURERS: List[Dict[str, Any]] = [

    # ── Life Insurance — Public ───────────────────────────────────────────────
    {
        "name": "Life Insurance Corporation of India",
        "short_name": "LIC",
        "type": "public_life",
        "csr": 98.49,
        "solvency_ratio": 1.85,
        "complaint_ratio": 4.12,
        "market_share": 64.1,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 15,
        "digital_score": 6,
        "irdai_reg_no": "512",
        "headquarters": "Mumbai",
        "established_year": 1956,
    },
    {
        "name": "SBI Life Insurance",
        "short_name": "SBI Life",
        "type": "private_life",
        "csr": 95.03,
        "solvency_ratio": 2.14,
        "complaint_ratio": 2.85,
        "market_share": 7.2,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 10,
        "digital_score": 8,
        "irdai_reg_no": "111",
        "headquarters": "Mumbai",
        "established_year": 2001,
    },

    # ── Life Insurance — Private ──────────────────────────────────────────────
    {
        "name": "HDFC Life Insurance",
        "short_name": "HDFC Life",
        "type": "private_life",
        "csr": 99.5,
        "solvency_ratio": 1.88,
        "complaint_ratio": 1.93,
        "market_share": 7.8,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 7,
        "digital_score": 9,
        "irdai_reg_no": "101",
        "headquarters": "Mumbai",
        "established_year": 2000,
    },
    {
        "name": "ICICI Prudential Life Insurance",
        "short_name": "ICICI Pru Life",
        "type": "private_life",
        "csr": 97.9,
        "solvency_ratio": 2.12,
        "complaint_ratio": 2.11,
        "market_share": 5.9,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 8,
        "digital_score": 9,
        "irdai_reg_no": "105",
        "headquarters": "Mumbai",
        "established_year": 2001,
    },
    {
        "name": "Max Life Insurance",
        "short_name": "Max Life",
        "type": "private_life",
        "csr": 99.51,
        "solvency_ratio": 2.01,
        "complaint_ratio": 1.56,
        "market_share": 3.5,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 6,
        "digital_score": 8,
        "irdai_reg_no": "104",
        "headquarters": "New Delhi",
        "established_year": 2000,
    },
    {
        "name": "Bajaj Allianz Life Insurance",
        "short_name": "Bajaj Allianz Life",
        "type": "private_life",
        "csr": 99.04,
        "solvency_ratio": 6.87,
        "complaint_ratio": 2.44,
        "market_share": 3.2,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 9,
        "digital_score": 8,
        "irdai_reg_no": "116",
        "headquarters": "Pune",
        "established_year": 2001,
    },
    {
        "name": "Kotak Mahindra Life Insurance",
        "short_name": "Kotak Life",
        "type": "private_life",
        "csr": 98.82,
        "solvency_ratio": 2.84,
        "complaint_ratio": 1.88,
        "market_share": 2.1,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 8,
        "digital_score": 8,
        "irdai_reg_no": "107",
        "headquarters": "Mumbai",
        "established_year": 2001,
    },
    {
        "name": "Tata AIA Life Insurance",
        "short_name": "Tata AIA Life",
        "type": "private_life",
        "csr": 99.01,
        "solvency_ratio": 2.06,
        "complaint_ratio": 1.72,
        "market_share": 2.0,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 7,
        "digital_score": 9,
        "irdai_reg_no": "110",
        "headquarters": "Mumbai",
        "established_year": 2001,
    },
    {
        "name": "PNB MetLife India Insurance",
        "short_name": "PNB MetLife",
        "type": "private_life",
        "csr": 99.15,
        "solvency_ratio": 2.09,
        "complaint_ratio": 2.03,
        "market_share": 1.5,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 9,
        "digital_score": 7,
        "irdai_reg_no": "117",
        "headquarters": "Mumbai",
        "established_year": 2001,
    },
    {
        "name": "Aditya Birla Sun Life Insurance",
        "short_name": "ABSLI",
        "type": "private_life",
        "csr": 98.03,
        "solvency_ratio": 1.79,
        "complaint_ratio": 2.67,
        "market_share": 2.8,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 10,
        "digital_score": 8,
        "irdai_reg_no": "109",
        "headquarters": "Mumbai",
        "established_year": 2000,
    },

    # ── Health Insurance — Standalone (SAHI) ─────────────────────────────────
    {
        "name": "Star Health and Allied Insurance",
        "short_name": "Star Health",
        "type": "standalone_health",
        "csr": 90.5,
        "solvency_ratio": 1.72,
        "complaint_ratio": 5.81,
        "market_share": 2.9,
        "icr": 65.09,
        "network_hospitals": 14000,
        "claim_settlement_time_avg": 7,
        "digital_score": 8,
        "irdai_reg_no": "129",
        "headquarters": "Chennai",
        "established_year": 2006,
    },
    {
        "name": "Niva Bupa Health Insurance",
        "short_name": "Niva Bupa",
        "type": "standalone_health",
        "csr": 90.4,
        "solvency_ratio": 1.69,
        "complaint_ratio": 4.44,
        "market_share": 1.8,
        "icr": 58.34,
        "network_hospitals": 10000,
        "claim_settlement_time_avg": 6,
        "digital_score": 9,
        "irdai_reg_no": "145",
        "headquarters": "New Delhi",
        "established_year": 2008,
    },
    {
        "name": "Care Health Insurance",
        "short_name": "Care Health",
        "type": "standalone_health",
        "csr": 90.6,
        "solvency_ratio": 1.61,
        "complaint_ratio": 4.88,
        "market_share": 1.5,
        "icr": 55.6,
        "network_hospitals": 19000,
        "claim_settlement_time_avg": 8,
        "digital_score": 8,
        "irdai_reg_no": "148",
        "headquarters": "Gurugram",
        "established_year": 2012,
    },
    {
        "name": "ManipalCigna Health Insurance",
        "short_name": "ManipalCigna",
        "type": "standalone_health",
        "csr": 88.0,
        "solvency_ratio": 1.58,
        "complaint_ratio": 5.22,
        "market_share": 0.8,
        "icr": 63.3,
        "network_hospitals": 8700,
        "claim_settlement_time_avg": 9,
        "digital_score": 8,
        "irdai_reg_no": "151",
        "headquarters": "Mumbai",
        "established_year": 2014,
    },
    {
        "name": "Aditya Birla Health Insurance",
        "short_name": "ABHI",
        "type": "standalone_health",
        "csr": 87.5,
        "solvency_ratio": 1.55,
        "complaint_ratio": 4.95,
        "market_share": 0.9,
        "icr": 66.5,
        "network_hospitals": 10000,
        "claim_settlement_time_avg": 7,
        "digital_score": 9,
        "irdai_reg_no": "153",
        "headquarters": "Mumbai",
        "established_year": 2015,
    },

    # ── General / Multi-line (Health + Motor + Other) ─────────────────────────
    {
        "name": "HDFC ERGO General Insurance",
        "short_name": "HDFC ERGO",
        "type": "private_general",
        "csr": 92.1,
        "solvency_ratio": 1.81,
        "complaint_ratio": 3.54,
        "market_share": 5.2,
        "icr": 82.4,
        "network_hospitals": 13000,
        "claim_settlement_time_avg": 8,
        "digital_score": 9,
        "irdai_reg_no": "146",
        "headquarters": "Mumbai",
        "established_year": 2002,
    },
    {
        "name": "ICICI Lombard General Insurance",
        "short_name": "ICICI Lombard",
        "type": "private_general",
        "csr": 90.8,
        "solvency_ratio": 2.39,
        "complaint_ratio": 3.21,
        "market_share": 7.4,
        "icr": 80.1,
        "network_hospitals": 8000,
        "claim_settlement_time_avg": 7,
        "digital_score": 9,
        "irdai_reg_no": "115",
        "headquarters": "Mumbai",
        "established_year": 2001,
    },
    {
        "name": "Bajaj Allianz General Insurance",
        "short_name": "Bajaj Allianz General",
        "type": "private_general",
        "csr": 88.5,
        "solvency_ratio": 2.01,
        "complaint_ratio": 3.88,
        "market_share": 5.5,
        "icr": 78.9,
        "network_hospitals": 6500,
        "claim_settlement_time_avg": 9,
        "digital_score": 8,
        "irdai_reg_no": "113",
        "headquarters": "Pune",
        "established_year": 2001,
    },
    {
        "name": "New India Assurance",
        "short_name": "New India",
        "type": "public_general",
        "csr": 86.0,
        "solvency_ratio": 1.55,
        "complaint_ratio": 6.44,
        "market_share": 8.1,
        "icr": 88.5,
        "network_hospitals": 15000,
        "claim_settlement_time_avg": 21,
        "digital_score": 6,
        "irdai_reg_no": "190",
        "headquarters": "Mumbai",
        "established_year": 1919,
    },
    {
        "name": "Oriental Insurance",
        "short_name": "Oriental Insurance",
        "type": "public_general",
        "csr": 83.2,
        "solvency_ratio": 1.52,
        "complaint_ratio": 7.12,
        "market_share": 4.6,
        "icr": 91.2,
        "network_hospitals": 8000,
        "claim_settlement_time_avg": 25,
        "digital_score": 5,
        "irdai_reg_no": "556",
        "headquarters": "New Delhi",
        "established_year": 1947,
    },
    {
        "name": "United India Insurance",
        "short_name": "United India",
        "type": "public_general",
        "csr": 84.1,
        "solvency_ratio": 1.51,
        "complaint_ratio": 7.44,
        "market_share": 4.4,
        "icr": 93.4,
        "network_hospitals": 7000,
        "claim_settlement_time_avg": 24,
        "digital_score": 5,
        "irdai_reg_no": "545",
        "headquarters": "Chennai",
        "established_year": 1938,
    },
    {
        "name": "National Insurance",
        "short_name": "National Insurance",
        "type": "public_general",
        "csr": 82.5,
        "solvency_ratio": 1.50,
        "complaint_ratio": 8.01,
        "market_share": 4.1,
        "icr": 95.1,
        "network_hospitals": 6000,
        "claim_settlement_time_avg": 27,
        "digital_score": 5,
        "irdai_reg_no": "058",
        "headquarters": "Kolkata",
        "established_year": 1906,
    },
    {
        "name": "TATA AIG General Insurance",
        "short_name": "TATA AIG",
        "type": "private_general",
        "csr": 89.4,
        "solvency_ratio": 1.91,
        "complaint_ratio": 3.66,
        "market_share": 3.6,
        "icr": 76.3,
        "network_hospitals": 7000,
        "claim_settlement_time_avg": 10,
        "digital_score": 8,
        "irdai_reg_no": "108",
        "headquarters": "Mumbai",
        "established_year": 2001,
    },
    {
        "name": "Reliance General Insurance",
        "short_name": "Reliance General",
        "type": "private_general",
        "csr": 86.8,
        "solvency_ratio": 1.69,
        "complaint_ratio": 5.34,
        "market_share": 2.8,
        "icr": 84.2,
        "network_hospitals": 5000,
        "claim_settlement_time_avg": 14,
        "digital_score": 7,
        "irdai_reg_no": "103",
        "headquarters": "Mumbai",
        "established_year": 2000,
    },
    {
        "name": "Digit Insurance",
        "short_name": "Digit",
        "type": "private_general",
        "csr": 96.0,
        "solvency_ratio": 1.71,
        "complaint_ratio": 2.11,
        "market_share": 2.2,
        "icr": 66.9,
        "network_hospitals": 5000,
        "claim_settlement_time_avg": 5,
        "digital_score": 9,
        "irdai_reg_no": "158",
        "headquarters": "Bengaluru",
        "established_year": 2017,
    },
    {
        "name": "Royal Sundaram General Insurance",
        "short_name": "Royal Sundaram",
        "type": "private_general",
        "csr": 87.1,
        "solvency_ratio": 1.78,
        "complaint_ratio": 4.22,
        "market_share": 1.5,
        "icr": 79.5,
        "network_hospitals": 4500,
        "claim_settlement_time_avg": 12,
        "digital_score": 7,
        "irdai_reg_no": "102",
        "headquarters": "Chennai",
        "established_year": 2001,
    },
    {
        "name": "Future Generali India Insurance",
        "short_name": "Future Generali",
        "type": "private_general",
        "csr": 86.3,
        "solvency_ratio": 1.64,
        "complaint_ratio": 4.88,
        "market_share": 1.2,
        "icr": 81.4,
        "network_hospitals": 4000,
        "claim_settlement_time_avg": 13,
        "digital_score": 7,
        "irdai_reg_no": "132",
        "headquarters": "Mumbai",
        "established_year": 2007,
    },
    {
        "name": "Kotak General Insurance",
        "short_name": "Kotak General",
        "type": "private_general",
        "csr": 91.2,
        "solvency_ratio": 1.93,
        "complaint_ratio": 2.98,
        "market_share": 0.9,
        "icr": 74.1,
        "network_hospitals": 4200,
        "claim_settlement_time_avg": 9,
        "digital_score": 8,
        "irdai_reg_no": "152",
        "headquarters": "Mumbai",
        "established_year": 2015,
    },
    {
        "name": "SBI General Insurance",
        "short_name": "SBI General",
        "type": "private_general",
        "csr": 88.2,
        "solvency_ratio": 1.85,
        "complaint_ratio": 3.99,
        "market_share": 2.1,
        "icr": 80.7,
        "network_hospitals": 5500,
        "claim_settlement_time_avg": 11,
        "digital_score": 7,
        "irdai_reg_no": "144",
        "headquarters": "Mumbai",
        "established_year": 2010,
    },
    {
        "name": "Edelweiss General Insurance",
        "short_name": "Edelweiss General",
        "type": "private_general",
        "csr": 90.1,
        "solvency_ratio": 1.75,
        "complaint_ratio": 2.77,
        "market_share": 0.4,
        "icr": 72.3,
        "network_hospitals": 3000,
        "claim_settlement_time_avg": 8,
        "digital_score": 8,
        "irdai_reg_no": "157",
        "headquarters": "Mumbai",
        "established_year": 2016,
    },
    {
        "name": "Go Digit Life Insurance",
        "short_name": "Digit Life",
        "type": "private_life",
        "csr": 97.1,
        "solvency_ratio": 1.91,
        "complaint_ratio": 1.44,
        "market_share": 0.3,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 5,
        "digital_score": 9,
        "irdai_reg_no": "159",
        "headquarters": "Bengaluru",
        "established_year": 2021,
    },
    {
        "name": "Acko General Insurance",
        "short_name": "Acko",
        "type": "private_general",
        "csr": 97.5,
        "solvency_ratio": 1.66,
        "complaint_ratio": 1.22,
        "market_share": 0.5,
        "icr": 68.4,
        "network_hospitals": 3000,
        "claim_settlement_time_avg": 4,
        "digital_score": 10,
        "irdai_reg_no": "157",
        "headquarters": "Bengaluru",
        "established_year": 2016,
    },

    # ── Life Insurance — Private (Extended) ───────────────────────────────────
    {
        "name": "Canara HSBC Life Insurance",
        "short_name": "Canara HSBC Life",
        "type": "private_life",
        "csr": 98.1,
        "solvency_ratio": 2.15,
        "complaint_ratio": 1.82,
        "market_share": 1.2,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 8,
        "digital_score": 8,
        "irdai_reg_no": "136",
        "headquarters": "Gurugram",
        "established_year": 2008,
    },
    {
        "name": "IndiaFirst Life Insurance",
        "short_name": "IndiaFirst Life",
        "type": "private_life",
        "csr": 96.7,
        "solvency_ratio": 1.95,
        "complaint_ratio": 2.44,
        "market_share": 0.8,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 10,
        "digital_score": 7,
        "irdai_reg_no": "143",
        "headquarters": "Mumbai",
        "established_year": 2009,
    },
    {
        "name": "Shriram Life Insurance",
        "short_name": "Shriram Life",
        "type": "private_life",
        "csr": 87.9,
        "solvency_ratio": 2.08,
        "complaint_ratio": 3.12,
        "market_share": 0.5,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 12,
        "digital_score": 7,
        "irdai_reg_no": "128",
        "headquarters": "Hyderabad",
        "established_year": 2005,
    },
    {
        "name": "Bharti AXA Life Insurance",
        "short_name": "Bharti AXA Life",
        "type": "private_life",
        "csr": 97.6,
        "solvency_ratio": 2.01,
        "complaint_ratio": 2.01,
        "market_share": 0.7,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 9,
        "digital_score": 8,
        "irdai_reg_no": "130",
        "headquarters": "Mumbai",
        "established_year": 2006,
    },
    {
        "name": "Star Union Dai-ichi Life Insurance",
        "short_name": "Star Union Dai-ichi",
        "type": "private_life",
        "csr": 95.3,
        "solvency_ratio": 1.88,
        "complaint_ratio": 2.88,
        "market_share": 0.3,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 11,
        "digital_score": 7,
        "irdai_reg_no": "142",
        "headquarters": "Mumbai",
        "established_year": 2009,
    },
    {
        "name": "Aviva Life Insurance India",
        "short_name": "Aviva Life",
        "type": "private_life",
        "csr": 98.4,
        "solvency_ratio": 2.33,
        "complaint_ratio": 2.11,
        "market_share": 0.4,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 9,
        "digital_score": 7,
        "irdai_reg_no": "122",
        "headquarters": "Gurugram",
        "established_year": 2002,
    },
    {
        "name": "Bandhan Life Insurance",
        "short_name": "Bandhan Life",
        "type": "private_life",
        "csr": 99.1,
        "solvency_ratio": 2.02,
        "complaint_ratio": 1.55,
        "market_share": 0.2,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 8,
        "digital_score": 8,
        "irdai_reg_no": "138",
        "headquarters": "Mumbai",
        "established_year": 2008,
    },
    {
        "name": "Pramerica Life Insurance",
        "short_name": "Pramerica Life",
        "type": "private_life",
        "csr": 97.2,
        "solvency_ratio": 1.91,
        "complaint_ratio": 2.22,
        "market_share": 0.3,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 10,
        "digital_score": 7,
        "irdai_reg_no": "140",
        "headquarters": "Gurugram",
        "established_year": 2008,
    },
    {
        "name": "Edelweiss Tokio Life Insurance",
        "short_name": "Edelweiss Tokio Life",
        "type": "private_life",
        "csr": 98.1,
        "solvency_ratio": 2.12,
        "complaint_ratio": 2.01,
        "market_share": 0.2,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 9,
        "digital_score": 8,
        "irdai_reg_no": "147",
        "headquarters": "Mumbai",
        "established_year": 2011,
    },
    {
        "name": "Acko Life Insurance",
        "short_name": "Acko Life",
        "type": "private_life",
        "csr": 97.8,
        "solvency_ratio": 1.88,
        "complaint_ratio": 1.11,
        "market_share": 0.1,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 6,
        "digital_score": 9,
        "irdai_reg_no": "161",
        "headquarters": "Bengaluru",
        "established_year": 2021,
    },
    {
        "name": "Ageas Federal Life Insurance",
        "short_name": "Ageas Federal Life",
        "type": "private_life",
        "csr": 98.3,
        "solvency_ratio": 1.97,
        "complaint_ratio": 1.99,
        "market_share": 0.3,
        "icr": None,
        "network_hospitals": None,
        "claim_settlement_time_avg": 9,
        "digital_score": 7,
        "irdai_reg_no": "139",
        "headquarters": "Mumbai",
        "established_year": 2008,
    },

    # ── General Insurance — Private (Extended) ────────────────────────────────
    {
        "name": "IFFCO Tokio General Insurance",
        "short_name": "IFFCO Tokio",
        "type": "private_general",
        "csr": 88.5,
        "solvency_ratio": 1.77,
        "complaint_ratio": 4.11,
        "market_share": 2.3,
        "icr": 78.5,
        "network_hospitals": 5000,
        "claim_settlement_time_avg": 12,
        "digital_score": 7,
        "irdai_reg_no": "106",
        "headquarters": "Gurugram",
        "established_year": 2000,
    },
    {
        "name": "Liberty General Insurance",
        "short_name": "Liberty General",
        "type": "private_general",
        "csr": 89.1,
        "solvency_ratio": 1.82,
        "complaint_ratio": 3.77,
        "market_share": 0.7,
        "icr": 71.3,
        "network_hospitals": 3500,
        "claim_settlement_time_avg": 11,
        "digital_score": 7,
        "irdai_reg_no": "150",
        "headquarters": "Mumbai",
        "established_year": 2013,
    },
    {
        "name": "Chola MS General Insurance",
        "short_name": "Chola MS",
        "type": "private_general",
        "csr": 87.8,
        "solvency_ratio": 1.71,
        "complaint_ratio": 4.55,
        "market_share": 1.1,
        "icr": 80.2,
        "network_hospitals": 4000,
        "claim_settlement_time_avg": 14,
        "digital_score": 7,
        "irdai_reg_no": "123",
        "headquarters": "Chennai",
        "established_year": 2001,
    },
    {
        "name": "Universal Sompo General Insurance",
        "short_name": "Universal Sompo",
        "type": "private_general",
        "csr": 85.9,
        "solvency_ratio": 1.63,
        "complaint_ratio": 5.02,
        "market_share": 0.6,
        "icr": 82.1,
        "network_hospitals": 3000,
        "claim_settlement_time_avg": 16,
        "digital_score": 7,
        "irdai_reg_no": "134",
        "headquarters": "Mumbai",
        "established_year": 2007,
    },
    {
        "name": "Navi General Insurance",
        "short_name": "Navi General",
        "type": "private_general",
        "csr": 95.2,
        "solvency_ratio": 1.69,
        "complaint_ratio": 1.88,
        "market_share": 0.3,
        "icr": 65.4,
        "network_hospitals": 2500,
        "claim_settlement_time_avg": 5,
        "digital_score": 9,
        "irdai_reg_no": "155",
        "headquarters": "Bengaluru",
        "established_year": 2016,
    },
    {
        "name": "Raheja QBE General Insurance",
        "short_name": "Raheja QBE",
        "type": "private_general",
        "csr": 84.3,
        "solvency_ratio": 1.58,
        "complaint_ratio": 5.44,
        "market_share": 0.2,
        "icr": 83.7,
        "network_hospitals": 2000,
        "claim_settlement_time_avg": 18,
        "digital_score": 7,
        "irdai_reg_no": "135",
        "headquarters": "Mumbai",
        "established_year": 2008,
    },
    {
        "name": "Magma HDI General Insurance",
        "short_name": "Magma HDI",
        "type": "private_general",
        "csr": 86.6,
        "solvency_ratio": 1.66,
        "complaint_ratio": 4.33,
        "market_share": 0.5,
        "icr": 77.8,
        "network_hospitals": 2500,
        "claim_settlement_time_avg": 15,
        "digital_score": 7,
        "irdai_reg_no": "141",
        "headquarters": "Kolkata",
        "established_year": 2009,
    },
    {
        "name": "Zurich Kotak General Insurance",
        "short_name": "Zurich Kotak General",
        "type": "private_general",
        "csr": 91.5,
        "solvency_ratio": 1.95,
        "complaint_ratio": 2.78,
        "market_share": 0.8,
        "icr": 73.5,
        "network_hospitals": 4000,
        "claim_settlement_time_avg": 9,
        "digital_score": 8,
        "irdai_reg_no": "152",
        "headquarters": "Mumbai",
        "established_year": 2015,
    },
    {
        "name": "Kshema General Insurance",
        "short_name": "Kshema General",
        "type": "private_general",
        "csr": 83.1,
        "solvency_ratio": 1.52,
        "complaint_ratio": 6.11,
        "market_share": 0.1,
        "icr": 85.4,
        "network_hospitals": 1500,
        "claim_settlement_time_avg": 22,
        "digital_score": 7,
        "irdai_reg_no": "160",
        "headquarters": "Chennai",
        "established_year": 2019,
    },
]

# ── Cypher ─────────────────────────────────────────────────────────────────────

_MERGE_INSURER = """
MERGE (i:Insurer {name: $name})
SET
  i.short_name                  = $short_name,
  i.type                        = $type,
  i.csr                         = $csr,
  i.solvency_ratio              = $solvency_ratio,
  i.complaint_ratio             = $complaint_ratio,
  i.market_share                = $market_share,
  i.icr                         = $icr,
  i.network_hospitals           = $network_hospitals,
  i.claim_settlement_time_avg   = $claim_settlement_time_avg,
  i.digital_score               = $digital_score,
  i.irdai_reg_no                = $irdai_reg_no,
  i.headquarters                = $headquarters,
  i.established_year            = $established_year,
  i.updated_at                  = datetime()
RETURN i.name AS name
"""


async def seed_insurers(client: Neo4jClient) -> None:
    """
    MERGE all Insurer nodes into Neo4j. Idempotent — safe to re-run.
    """
    logger.info("seed_insurers_start", count=len(INSURERS))
    succeeded = await client.execute_batch(
        _MERGE_INSURER,
        param_list=INSURERS,
        query_name="seed_insurers",
    )
    logger.info("seed_insurers_complete", succeeded=succeeded, total=len(INSURERS))
