"""
Product Seed Data
==================
50+ real Indian insurance products across categories.
All sum-insured figures in INR (raw), premium figures are annual approximations.

Run via: python -m hibiscus.knowledge.graph.seed
"""
from typing import Any, Dict, List, Optional

from hibiscus.knowledge.graph.client import Neo4jClient
from hibiscus.observability.logger import get_logger

logger = get_logger("hibiscus.kg.seed.products")

# ── Helper ─────────────────────────────────────────────────────────────────────

def L(lakhs: float) -> int:
    """Convert lakhs to INR."""
    return int(lakhs * 100_000)


def Cr(crores: float) -> int:
    """Convert crores to INR."""
    return int(crores * 10_000_000)


# ── Data ───────────────────────────────────────────────────────────────────────
# Field reference:
#   name                 : str   — unique product name
#   insurer_name         : str   — must match Insurer.name in KG
#   category             : str   — "health" | "life_term" | "life_endowment" | "life_money_back"
#                                   | "life_savings" | "ulip" | "motor" | "travel" | "personal_accident"
#   type                 : str   — subcategory / product type key
#   sum_insured_min      : int   — minimum SI in INR
#   sum_insured_max      : int   — maximum SI in INR (None = unlimited)
#   premium_range_min    : int   — approx annual premium for base SI (INR)
#   premium_range_max    : int   — approx annual premium for max SI (INR)
#   key_features         : list  — top 5 features
#   exclusion_count      : int   — number of listed exclusions
#   sub_limit_count      : int   — number of sub-limits / caps
#   waiting_periods      : dict  — { "pre_existing": days, "specific": days, "initial": days }
#   copay_structure      : str   — e.g. "0%", "10% for age 61+", "20% senior"
#   room_rent_limit      : str   — e.g. "No limit", "1% of SI per day", "Single AC room"
#   eazr_score           : float — EAZR proprietary score (0-10)

PRODUCTS: List[Dict[str, Any]] = [

    # ── Health Insurance ──────────────────────────────────────────────────────

    {
        "name": "Star Comprehensive Individual Health Insurance",
        "insurer_name": "Star Health and Allied Insurance",
        "category": "health",
        "type": "individual_health",
        "sum_insured_min": L(5),
        "sum_insured_max": Cr(1),
        "premium_range_min": 7500,
        "premium_range_max": 80000,
        "key_features": [
            "No room rent limit",
            "No copay",
            "No sub-limit on major procedures",
            "In-patient hospitalisation covered",
            "AYUSH treatment covered",
        ],
        "exclusion_count": 12,
        "sub_limit_count": 3,
        "waiting_periods": {"pre_existing": 1095, "specific": 730, "initial": 30},
        "copay_structure": "0%",
        "room_rent_limit": "No limit",
        "eazr_score": 8.2,
        "restore_benefit": True,
        "annual_health_checkup": True,
        "no_claim_bonus": "50% of SI per year, max 100%",
    },
    {
        "name": "Star Health Young Star Insurance Policy",
        "insurer_name": "Star Health and Allied Insurance",
        "category": "health",
        "type": "individual_health",
        "sum_insured_min": L(3),
        "sum_insured_max": L(25),
        "premium_range_min": 4800,
        "premium_range_max": 25000,
        "key_features": [
            "Designed for individuals up to age 40",
            "AYUSH covered",
            "Renewable for life",
            "Wellness benefits",
            "OPD discount on renewal",
        ],
        "exclusion_count": 14,
        "sub_limit_count": 5,
        "waiting_periods": {"pre_existing": 1095, "specific": 730, "initial": 30},
        "copay_structure": "0%",
        "room_rent_limit": "Single AC room",
        "eazr_score": 7.8,
        "age_limit": 40,
    },
    {
        "name": "Niva Bupa Aspire",
        "insurer_name": "Niva Bupa Health Insurance",
        "category": "health",
        "type": "individual_health",
        "sum_insured_min": L(5),
        "sum_insured_max": Cr(1),
        "premium_range_min": 8000,
        "premium_range_max": 90000,
        "key_features": [
            "No room rent limit",
            "Zero copay",
            "Booster+ benefit (unused SI carries forward)",
            "No sub-limits on procedures",
            "Global cover option",
        ],
        "exclusion_count": 11,
        "sub_limit_count": 2,
        "waiting_periods": {"pre_existing": 1095, "specific": 730, "initial": 30},
        "copay_structure": "0%",
        "room_rent_limit": "No limit",
        "eazr_score": 8.5,
        "restore_benefit": True,
        "global_cover": True,
    },
    {
        "name": "Niva Bupa ReAssure 2.0",
        "insurer_name": "Niva Bupa Health Insurance",
        "category": "health",
        "type": "individual_health",
        "sum_insured_min": L(5),
        "sum_insured_max": Cr(3),
        "premium_range_min": 9500,
        "premium_range_max": 150000,
        "key_features": [
            "Unlimited restore of base SI",
            "Lock the Clock — premium stays same if no claim",
            "ReAssure+ benefit",
            "No room rent limit",
            "International second opinion",
        ],
        "exclusion_count": 10,
        "sub_limit_count": 1,
        "waiting_periods": {"pre_existing": 1095, "specific": 730, "initial": 30},
        "copay_structure": "0%",
        "room_rent_limit": "No limit",
        "eazr_score": 8.8,
        "unlimited_restore": True,
        "lock_the_clock": True,
    },
    {
        "name": "HDFC ERGO Optima Restore",
        "insurer_name": "HDFC ERGO General Insurance",
        "category": "health",
        "type": "individual_health",
        "sum_insured_min": L(3),
        "sum_insured_max": L(50),
        "premium_range_min": 6500,
        "premium_range_max": 55000,
        "key_features": [
            "Restore benefit — 100% SI restored once per year",
            "Multiplier benefit — SI increases 50% each claim-free year",
            "No sub-limit on room rent",
            "Day-care procedures covered",
            "AYUSH covered",
        ],
        "exclusion_count": 13,
        "sub_limit_count": 4,
        "waiting_periods": {"pre_existing": 1095, "specific": 730, "initial": 30},
        "copay_structure": "0%",
        "room_rent_limit": "No limit",
        "eazr_score": 8.0,
        "restore_benefit": True,
        "multiplier_benefit": True,
    },
    {
        "name": "HDFC ERGO Optima Secure",
        "insurer_name": "HDFC ERGO General Insurance",
        "category": "health",
        "type": "individual_health",
        "sum_insured_min": L(10),
        "sum_insured_max": Cr(2),
        "premium_range_min": 12000,
        "premium_range_max": 120000,
        "key_features": [
            "4X Secure benefit — SI enhanced 4x at no extra cost",
            "No room rent cap",
            "Zero copay",
            "No sub-limits",
            "International treatment covered",
        ],
        "exclusion_count": 10,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 1095, "specific": 730, "initial": 30},
        "copay_structure": "0%",
        "room_rent_limit": "No limit",
        "eazr_score": 8.4,
    },
    {
        "name": "Care Supreme Health Insurance",
        "insurer_name": "Care Health Insurance",
        "category": "health",
        "type": "individual_health",
        "sum_insured_min": L(10),
        "sum_insured_max": Cr(1),
        "premium_range_min": 11000,
        "premium_range_max": 85000,
        "key_features": [
            "No copay",
            "No room rent limit",
            "Instant cashless approval in 30 min",
            "Annual health check-up",
            "Unlimited teleconsultation",
        ],
        "exclusion_count": 11,
        "sub_limit_count": 2,
        "waiting_periods": {"pre_existing": 1095, "specific": 730, "initial": 30},
        "copay_structure": "0%",
        "room_rent_limit": "No limit",
        "eazr_score": 8.3,
        "cashless_approval_mins": 30,
    },
    {
        "name": "ManipalCigna ProHealth Plus",
        "insurer_name": "ManipalCigna Health Insurance",
        "category": "health",
        "type": "individual_health",
        "sum_insured_min": L(3),
        "sum_insured_max": Cr(1),
        "premium_range_min": 7200,
        "premium_range_max": 75000,
        "key_features": [
            "Global coverage option",
            "Maternity benefit",
            "Restore benefit",
            "Day-care procedures",
            "AYUSH covered",
        ],
        "exclusion_count": 14,
        "sub_limit_count": 5,
        "waiting_periods": {"pre_existing": 1095, "specific": 730, "initial": 30},
        "copay_structure": "0%",
        "room_rent_limit": "1% of SI per day",
        "eazr_score": 7.9,
    },
    {
        "name": "Aditya Birla Activ One",
        "insurer_name": "Aditya Birla Health Insurance",
        "category": "health",
        "type": "individual_health",
        "sum_insured_min": L(10),
        "sum_insured_max": Cr(6),
        "premium_range_min": 13000,
        "premium_range_max": 200000,
        "key_features": [
            "HealthReturns — earn premium back for staying healthy",
            "Chronic Management Program",
            "No room rent limit",
            "Zero copay",
            "Global Emergency Cover",
        ],
        "exclusion_count": 10,
        "sub_limit_count": 1,
        "waiting_periods": {"pre_existing": 1095, "specific": 730, "initial": 30},
        "copay_structure": "0%",
        "room_rent_limit": "No limit",
        "eazr_score": 8.6,
        "wellness_benefits": True,
        "health_returns": True,
    },
    {
        "name": "ICICI Lombard Complete Health Insurance",
        "insurer_name": "ICICI Lombard General Insurance",
        "category": "health",
        "type": "individual_health",
        "sum_insured_min": L(3),
        "sum_insured_max": L(50),
        "premium_range_min": 6800,
        "premium_range_max": 52000,
        "key_features": [
            "Cashless at 8000+ hospitals",
            "Day-care procedures",
            "AYUSH covered",
            "Annual health check-up",
            "Restoration benefit",
        ],
        "exclusion_count": 15,
        "sub_limit_count": 6,
        "waiting_periods": {"pre_existing": 1095, "specific": 730, "initial": 30},
        "copay_structure": "0%",
        "room_rent_limit": "Single AC room",
        "eazr_score": 7.7,
    },
    {
        "name": "Digit Health Insurance",
        "insurer_name": "Digit Insurance",
        "category": "health",
        "type": "individual_health",
        "sum_insured_min": L(2),
        "sum_insured_max": L(25),
        "premium_range_min": 5500,
        "premium_range_max": 28000,
        "key_features": [
            "Paperless digital claims",
            "Restore benefit",
            "Day-care procedures",
            "Easy online purchase",
            "No-claim bonus",
        ],
        "exclusion_count": 13,
        "sub_limit_count": 4,
        "waiting_periods": {"pre_existing": 1095, "specific": 730, "initial": 30},
        "copay_structure": "0%",
        "room_rent_limit": "Single AC room",
        "eazr_score": 7.5,
        "digital_claims": True,
    },
    {
        "name": "Acko Platinum Health Insurance",
        "insurer_name": "Acko General Insurance",
        "category": "health",
        "type": "individual_health",
        "sum_insured_min": L(10),
        "sum_insured_max": Cr(1),
        "premium_range_min": 10000,
        "premium_range_max": 80000,
        "key_features": [
            "Zero copay",
            "No room rent cap",
            "In-app claim filing",
            "Cashless everywhere within network",
            "100% digital — no paperwork",
        ],
        "exclusion_count": 11,
        "sub_limit_count": 2,
        "waiting_periods": {"pre_existing": 1095, "specific": 730, "initial": 30},
        "copay_structure": "0%",
        "room_rent_limit": "No limit",
        "eazr_score": 8.1,
        "zero_copay": True,
    },
    {
        "name": "New India Floater Mediclaim Policy",
        "insurer_name": "New India Assurance",
        "category": "health",
        "type": "family_floater",
        "sum_insured_min": L(2),
        "sum_insured_max": L(15),
        "premium_range_min": 5000,
        "premium_range_max": 30000,
        "key_features": [
            "Government-backed insurer",
            "Wide hospital network",
            "Family floater",
            "Maternity benefit",
            "AYUSH covered",
        ],
        "exclusion_count": 18,
        "sub_limit_count": 8,
        "waiting_periods": {"pre_existing": 1095, "specific": 730, "initial": 30},
        "copay_structure": "0%",
        "room_rent_limit": "1% of SI per day",
        "eazr_score": 6.5,
        "government_backed": True,
    },
    {
        "name": "Star Senior Citizens Red Carpet Health Insurance",
        "insurer_name": "Star Health and Allied Insurance",
        "category": "health",
        "type": "senior_citizen_health",
        "sum_insured_min": L(1),
        "sum_insured_max": L(25),
        "premium_range_min": 15000,
        "premium_range_max": 80000,
        "key_features": [
            "Designed for age 60-75",
            "No pre-policy medical check-up for SI up to 10L",
            "Pre-existing diseases covered after 12 months",
            "Domiciliary hospitalisation",
            "Annual health check-up",
        ],
        "exclusion_count": 16,
        "sub_limit_count": 6,
        "waiting_periods": {"pre_existing": 365, "specific": 365, "initial": 30},
        "copay_structure": "10% on every claim",
        "room_rent_limit": "Single standard AC room",
        "eazr_score": 7.0,
        "target_segment": "senior_citizens",
        "min_entry_age": 60,
        "max_entry_age": 75,
    },
    {
        "name": "Niva Bupa Senior First Health Insurance",
        "insurer_name": "Niva Bupa Health Insurance",
        "category": "health",
        "type": "senior_citizen_health",
        "sum_insured_min": L(5),
        "sum_insured_max": L(25),
        "premium_range_min": 22000,
        "premium_range_max": 90000,
        "key_features": [
            "Pre-existing conditions covered from day 1 with day-1 PED add-on",
            "Designed for 55+ age group",
            "No room rent sub-limit",
            "Teleconsultation",
            "Annual preventive health check-up",
        ],
        "exclusion_count": 14,
        "sub_limit_count": 4,
        "waiting_periods": {"pre_existing": 1095, "specific": 730, "initial": 30},
        "copay_structure": "20% on claims",
        "room_rent_limit": "No limit",
        "eazr_score": 7.2,
        "target_segment": "senior_citizens",
        "min_entry_age": 55,
    },

    # ── Life — Term Insurance ─────────────────────────────────────────────────

    {
        "name": "HDFC Life Click2Protect Super",
        "insurer_name": "HDFC Life Insurance",
        "category": "life_term",
        "type": "term",
        "sum_insured_min": L(25),
        "sum_insured_max": Cr(10),
        "premium_range_min": 8500,
        "premium_range_max": 50000,
        "key_features": [
            "Life option, Life + CI option, Life Income option",
            "Return of premium option",
            "Whole life cover up to age 99",
            "Terminal illness benefit",
            "Waiver of premium on disability",
        ],
        "exclusion_count": 4,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 9.0,
        "plan_options": ["Life", "Life Plus", "Life Goal", "Life Income"],
        "return_of_premium": True,
        "whole_life_option": True,
    },
    {
        "name": "ICICI Pru iProtect Smart",
        "insurer_name": "ICICI Prudential Life Insurance",
        "category": "life_term",
        "type": "term",
        "sum_insured_min": L(25),
        "sum_insured_max": None,  # No upper limit
        "premium_range_min": 7900,
        "premium_range_max": 55000,
        "key_features": [
            "Life, Life + Health, All-in-One options",
            "Critical illness benefit — 34 CIs",
            "Accidental death benefit",
            "Terminal illness benefit",
            "Waiver of premium on CI or disability",
        ],
        "exclusion_count": 4,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 9.1,
        "ci_conditions_covered": 34,
        "unlimited_si": True,
    },
    {
        "name": "Max Life Smart Secure Plus Plan",
        "insurer_name": "Max Life Insurance",
        "category": "life_term",
        "type": "term",
        "sum_insured_min": L(25),
        "sum_insured_max": Cr(10),
        "premium_range_min": 8200,
        "premium_range_max": 48000,
        "key_features": [
            "Guaranteed cover with no claim bonus",
            "Special exit value",
            "Terminal illness benefit",
            "Critical illness add-on",
            "Accident cover add-on",
        ],
        "exclusion_count": 4,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 8.9,
        "special_exit_value": True,
    },
    {
        "name": "Tata AIA SRS Vitality Protect",
        "insurer_name": "Tata AIA Life Insurance",
        "category": "life_term",
        "type": "term",
        "sum_insured_min": L(50),
        "sum_insured_max": Cr(20),
        "premium_range_min": 8000,
        "premium_range_max": 52000,
        "key_features": [
            "Vitality wellness program integration",
            "Premium discount for healthy lifestyle",
            "Life cover + CI + disability",
            "Terminal illness benefit",
            "Waiver of premium on total disability",
        ],
        "exclusion_count": 4,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 8.8,
        "wellness_integration": True,
        "vitality_program": True,
    },
    {
        "name": "LIC Tech Term",
        "insurer_name": "Life Insurance Corporation of India",
        "category": "life_term",
        "type": "term",
        "sum_insured_min": L(50),
        "sum_insured_max": None,
        "premium_range_min": 9500,
        "premium_range_max": 60000,
        "key_features": [
            "Online pure term plan from LIC",
            "Level or increasing cover options",
            "Terminal illness benefit",
            "Premium waiver on disability add-on",
            "Government-backed insurer trust",
        ],
        "exclusion_count": 3,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 8.5,
        "government_backed": True,
    },
    {
        "name": "Bajaj Allianz Smart Protect Goal",
        "insurer_name": "Bajaj Allianz Life Insurance",
        "category": "life_term",
        "type": "term",
        "sum_insured_min": L(50),
        "sum_insured_max": Cr(10),
        "premium_range_min": 8400,
        "premium_range_max": 50000,
        "key_features": [
            "Life Goal protect option",
            "Return of premium option",
            "Increasing cover option",
            "Waiver of premium",
            "Accident benefit add-on",
        ],
        "exclusion_count": 4,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 8.7,
        "return_of_premium": True,
    },
    {
        "name": "SBI Life eShield Next",
        "insurer_name": "SBI Life Insurance",
        "category": "life_term",
        "type": "term",
        "sum_insured_min": L(50),
        "sum_insured_max": Cr(10),
        "premium_range_min": 8600,
        "premium_range_max": 48000,
        "key_features": [
            "Flex options — level, increasing, decreasing cover",
            "Better half benefit",
            "Accidental total permanent disability benefit",
            "Terminal illness benefit",
            "Spouse cover add-on",
        ],
        "exclusion_count": 4,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 8.6,
        "better_half_benefit": True,
    },
    {
        "name": "Kotak e-Term Plan",
        "insurer_name": "Kotak Mahindra Life Insurance",
        "category": "life_term",
        "type": "term",
        "sum_insured_min": L(25),
        "sum_insured_max": Cr(10),
        "premium_range_min": 8100,
        "premium_range_max": 46000,
        "key_features": [
            "Life, Life Plus, Life Income options",
            "Terminal illness benefit",
            "CI add-on (40 conditions)",
            "Accidental death benefit add-on",
            "Claim protection feature",
        ],
        "exclusion_count": 4,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 8.7,
        "ci_conditions_covered": 40,
    },
    {
        "name": "PNB MetLife Mera Term Plan Plus",
        "insurer_name": "PNB MetLife India Insurance",
        "category": "life_term",
        "type": "term",
        "sum_insured_min": L(25),
        "sum_insured_max": Cr(10),
        "premium_range_min": 8300,
        "premium_range_max": 47000,
        "key_features": [
            "Three plan options — Life Shield, Income Shield, Income Plus Shield",
            "Terminal illness benefit",
            "Accidental death benefit",
            "Waiver of future premiums",
            "Joint life option",
        ],
        "exclusion_count": 4,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 8.5,
        "joint_life": True,
    },

    # ── Life — Endowment / Savings ────────────────────────────────────────────

    {
        "name": "LIC Jeevan Umang",
        "insurer_name": "Life Insurance Corporation of India",
        "category": "life_endowment",
        "type": "whole_life",
        "sum_insured_min": L(2),
        "sum_insured_max": Cr(5),
        "premium_range_min": 25000,
        "premium_range_max": 300000,
        "key_features": [
            "Whole life cover up to age 100",
            "Annual survival benefit from end of premium-paying term",
            "Maturity benefit at age 100",
            "Loan facility",
            "Tax benefits under 80C and 10(10D)",
        ],
        "exclusion_count": 2,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 7.0,
        "irr_approx": 5.5,
        "note": "IRR approximately 5.5% — compare with PPF/FD before buying",
    },
    {
        "name": "LIC New Endowment Plan",
        "insurer_name": "Life Insurance Corporation of India",
        "category": "life_endowment",
        "type": "endowment",
        "sum_insured_min": L(1),
        "sum_insured_max": None,
        "premium_range_min": 18000,
        "premium_range_max": 200000,
        "key_features": [
            "Lump sum at maturity",
            "Death benefit",
            "Bonuses (simple reversionary)",
            "Loan facility",
            "Surrender value",
        ],
        "exclusion_count": 2,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 6.5,
        "irr_approx": 4.8,
        "note": "IRR approximately 4-5% — generally inferior to mutual funds + term combo",
    },
    {
        "name": "LIC New Money Back Plan — 20 Years",
        "insurer_name": "Life Insurance Corporation of India",
        "category": "life_endowment",
        "type": "money_back",
        "sum_insured_min": L(1),
        "sum_insured_max": None,
        "premium_range_min": 22000,
        "premium_range_max": 250000,
        "key_features": [
            "20% of SA paid every 5 years",
            "Final maturity benefit",
            "Death benefit = full SA regardless of survival benefits paid",
            "Bonuses",
            "Loan facility",
        ],
        "exclusion_count": 2,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 6.2,
        "irr_approx": 4.2,
        "note": "IRR approximately 4-4.5% — periodic liquidity feature, poor returns",
    },
    {
        "name": "HDFC Life Sanchay Plus",
        "insurer_name": "HDFC Life Insurance",
        "category": "life_savings",
        "type": "savings",
        "sum_insured_min": L(5),
        "sum_insured_max": Cr(5),
        "premium_range_min": 50000,
        "premium_range_max": 500000,
        "key_features": [
            "Guaranteed returns from day 1",
            "Long-term income option",
            "Life-long income option",
            "Tax-free maturity under 10(10D)",
            "Return of premium option",
        ],
        "exclusion_count": 2,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 7.5,
        "guaranteed_returns": True,
        "irr_approx": 6.0,
    },
    {
        "name": "ICICI Pru Guaranteed Income For Tomorrow",
        "insurer_name": "ICICI Prudential Life Insurance",
        "category": "life_savings",
        "type": "savings",
        "sum_insured_min": L(5),
        "sum_insured_max": Cr(5),
        "premium_range_min": 50000,
        "premium_range_max": 500000,
        "key_features": [
            "Guaranteed income from end of premium paying term",
            "Multiple plan options (Lump sum / Income / Early income)",
            "Life cover throughout",
            "Tax benefits",
            "Loan facility",
        ],
        "exclusion_count": 2,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 7.4,
        "guaranteed_returns": True,
        "irr_approx": 5.8,
    },
    {
        "name": "Max Life Savings Advantage Plan",
        "insurer_name": "Max Life Insurance",
        "category": "life_savings",
        "type": "savings",
        "sum_insured_min": L(5),
        "sum_insured_max": Cr(5),
        "premium_range_min": 50000,
        "premium_range_max": 500000,
        "key_features": [
            "Guaranteed additions each year",
            "Maturity benefit",
            "Life cover",
            "Loan option",
            "Tax-efficient",
        ],
        "exclusion_count": 2,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 7.3,
        "guaranteed_returns": True,
        "irr_approx": 5.7,
    },

    # ── ULIP ──────────────────────────────────────────────────────────────────

    {
        "name": "HDFC Life Click2Invest ULIP",
        "insurer_name": "HDFC Life Insurance",
        "category": "ulip",
        "type": "ulip",
        "sum_insured_min": L(1),
        "sum_insured_max": Cr(10),
        "premium_range_min": 12000,
        "premium_range_max": None,
        "key_features": [
            "Zero premium allocation charge",
            "Zero policy admin charge",
            "8 fund options",
            "Partial withdrawal after 5 years",
            "Loyalty additions",
        ],
        "exclusion_count": 3,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 7.2,
        "fund_options": 8,
        "lock_in_years": 5,
        "annual_premium_above_2_5L_taxable_gains": True,
    },
    {
        "name": "ICICI Pru Smart Life ULIP",
        "insurer_name": "ICICI Prudential Life Insurance",
        "category": "ulip",
        "type": "ulip",
        "sum_insured_min": L(1),
        "sum_insured_max": Cr(10),
        "premium_range_min": 24000,
        "premium_range_max": None,
        "key_features": [
            "18 fund options",
            "Automatic fund rebalancing",
            "Loyalty rewards",
            "Tax benefits on premium",
            "Partial withdrawal allowed after 5 years",
        ],
        "exclusion_count": 3,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 7.3,
        "fund_options": 18,
        "lock_in_years": 5,
        "annual_premium_above_2_5L_taxable_gains": True,
    },
    {
        "name": "Bajaj Allianz Goal Assure ULIP",
        "insurer_name": "Bajaj Allianz Life Insurance",
        "category": "ulip",
        "type": "ulip",
        "sum_insured_min": L(1),
        "sum_insured_max": Cr(5),
        "premium_range_min": 12000,
        "premium_range_max": None,
        "key_features": [
            "Return of mortality charges on maturity",
            "Zero premium allocation charge",
            "Loyalty additions",
            "Fund switching",
            "Partial withdrawal",
        ],
        "exclusion_count": 3,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 7.0,
        "fund_options": 10,
        "lock_in_years": 5,
        "annual_premium_above_2_5L_taxable_gains": True,
    },
    {
        "name": "SBI Life Smart Wealth Builder ULIP",
        "insurer_name": "SBI Life Insurance",
        "category": "ulip",
        "type": "ulip",
        "sum_insured_min": L(1),
        "sum_insured_max": Cr(5),
        "premium_range_min": 24000,
        "premium_range_max": None,
        "key_features": [
            "7 fund options",
            "Mortality charge waiver on maturity",
            "Loyalty additions from year 6",
            "Partial withdrawals",
            "Tax benefits",
        ],
        "exclusion_count": 3,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 7.1,
        "fund_options": 7,
        "lock_in_years": 5,
        "annual_premium_above_2_5L_taxable_gains": True,
    },

    # ── Motor Insurance ───────────────────────────────────────────────────────

    {
        "name": "HDFC ERGO Motor Own Damage Insurance",
        "insurer_name": "HDFC ERGO General Insurance",
        "category": "motor",
        "type": "motor_od",
        "sum_insured_min": 50000,
        "sum_insured_max": 10000000,
        "premium_range_min": 3000,
        "premium_range_max": 50000,
        "key_features": [
            "Cashless repair at 6800+ garages",
            "Overnight car repair",
            "Return-to-invoice add-on",
            "No-claim bonus (up to 50%)",
            "24x7 roadside assistance",
        ],
        "exclusion_count": 8,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 8.2,
        "cashless_garages": 6800,
        "digital_score": 9,
    },
    {
        "name": "Bajaj Allianz Motor Own Damage Insurance",
        "insurer_name": "Bajaj Allianz General Insurance",
        "category": "motor",
        "type": "motor_od",
        "sum_insured_min": 50000,
        "sum_insured_max": 10000000,
        "premium_range_min": 2800,
        "premium_range_max": 48000,
        "key_features": [
            "Cashless at 4000+ garages",
            "Drive Assure program",
            "Zero-depreciation add-on",
            "Consumables cover",
            "24x7 claims support",
        ],
        "exclusion_count": 8,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 8.0,
        "cashless_garages": 4000,
    },
    {
        "name": "ICICI Lombard Motor Insurance",
        "insurer_name": "ICICI Lombard General Insurance",
        "category": "motor",
        "type": "motor_od",
        "sum_insured_min": 50000,
        "sum_insured_max": 10000000,
        "premium_range_min": 2900,
        "premium_range_max": 49000,
        "key_features": [
            "InstaSpect — virtual car inspection",
            "Cashless at 5600+ garages",
            "Zero-depreciation add-on",
            "NCB protection",
            "Engine protect cover",
        ],
        "exclusion_count": 8,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 8.1,
        "cashless_garages": 5600,
    },
    {
        "name": "Digit Motor Insurance",
        "insurer_name": "Digit Insurance",
        "category": "motor",
        "type": "motor_od",
        "sum_insured_min": 50000,
        "sum_insured_max": 10000000,
        "premium_range_min": 2500,
        "premium_range_max": 45000,
        "key_features": [
            "Paperless — 100% online",
            "Pick-up and drop repair service",
            "Zero-depreciation",
            "Consumables covered",
            "Fast claim settlement",
        ],
        "exclusion_count": 7,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 8.5,
        "paperless": True,
    },
    {
        "name": "Acko Car Insurance",
        "insurer_name": "Acko General Insurance",
        "category": "motor",
        "type": "motor_od",
        "sum_insured_min": 50000,
        "sum_insured_max": 10000000,
        "premium_range_min": 2400,
        "premium_range_max": 44000,
        "key_features": [
            "Zero depreciation standard",
            "Doorstep pickup and repair",
            "1-hour claim approval",
            "100% digital",
            "No agent commission — lower premiums",
        ],
        "exclusion_count": 6,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 8.3,
        "zero_dep": True,
        "claim_approval_hrs": 1,
    },
    {
        "name": "New India Motor Third Party Insurance",
        "insurer_name": "New India Assurance",
        "category": "motor",
        "type": "motor_tp",
        "sum_insured_min": 750000,
        "sum_insured_max": None,
        "premium_range_min": 2094,
        "premium_range_max": 7897,
        "key_features": [
            "Mandatory by law",
            "Unlimited liability for death/injury",
            "Government-backed",
            "Standardised premium (IRDAI regulated)",
            "Covers third party property damage up to ₹7.5L",
        ],
        "exclusion_count": 4,
        "sub_limit_count": 0,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 7.5,
        "government_backed": True,
        "mandatory": True,
    },

    # ── Travel Insurance ──────────────────────────────────────────────────────

    {
        "name": "Bajaj Allianz Travel Elite Insurance",
        "insurer_name": "Bajaj Allianz General Insurance",
        "category": "travel",
        "type": "travel",
        "sum_insured_min": 500000,
        "sum_insured_max": 50000000,
        "premium_range_min": 800,
        "premium_range_max": 15000,
        "key_features": [
            "Medical expenses abroad",
            "Trip cancellation and curtailment",
            "Baggage loss",
            "Passport loss",
            "Emergency evacuation",
        ],
        "exclusion_count": 12,
        "sub_limit_count": 5,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 8.0,
    },
    {
        "name": "TATA AIG Travel Guard",
        "insurer_name": "TATA AIG General Insurance",
        "category": "travel",
        "type": "travel",
        "sum_insured_min": 500000,
        "sum_insured_max": 50000000,
        "premium_range_min": 900,
        "premium_range_max": 16000,
        "key_features": [
            "Medical cover with pre-existing cover option",
            "Trip cancellation",
            "Flight delay cover",
            "Loss of baggage",
            "Home burglary protection",
        ],
        "exclusion_count": 11,
        "sub_limit_count": 4,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 8.2,
    },
    {
        "name": "Digit Travel Insurance",
        "insurer_name": "Digit Insurance",
        "category": "travel",
        "type": "travel",
        "sum_insured_min": 500000,
        "sum_insured_max": 30000000,
        "premium_range_min": 750,
        "premium_range_max": 14000,
        "key_features": [
            "100% digital",
            "Medical cover abroad",
            "Trip cancellation",
            "Baggage loss",
            "Covid-19 covered",
        ],
        "exclusion_count": 10,
        "sub_limit_count": 4,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 8.0,
        "digital": True,
    },
    {
        "name": "HDFC ERGO Global Health Care Travel Insurance",
        "insurer_name": "HDFC ERGO General Insurance",
        "category": "travel",
        "type": "travel",
        "sum_insured_min": 1500000,
        "sum_insured_max": 100000000,
        "premium_range_min": 1200,
        "premium_range_max": 20000,
        "key_features": [
            "Worldwide medical cover",
            "Emergency medical evacuation",
            "Trip cancellation",
            "Personal liability cover",
            "Adventure sport cover option",
        ],
        "exclusion_count": 10,
        "sub_limit_count": 3,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 8.1,
    },
    {
        "name": "Care Travel Insurance",
        "insurer_name": "Care Health Insurance",
        "category": "travel",
        "type": "travel",
        "sum_insured_min": 500000,
        "sum_insured_max": 30000000,
        "premium_range_min": 800,
        "premium_range_max": 14500,
        "key_features": [
            "Medical cover abroad",
            "Trip cancellation",
            "Loss of baggage",
            "Passport loss",
            "Personal accident cover",
        ],
        "exclusion_count": 12,
        "sub_limit_count": 5,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 7.8,
    },

    # ── Personal Accident ─────────────────────────────────────────────────────

    {
        "name": "New India Personal Accident Policy",
        "insurer_name": "New India Assurance",
        "category": "personal_accident",
        "type": "personal_accident",
        "sum_insured_min": L(1),
        "sum_insured_max": Cr(1),
        "premium_range_min": 1500,
        "premium_range_max": 20000,
        "key_features": [
            "Accidental death benefit",
            "Permanent total disability",
            "Permanent partial disability",
            "Temporary total disability weekly benefit",
            "Education grant for dependent children",
        ],
        "exclusion_count": 8,
        "sub_limit_count": 2,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 7.5,
    },
    {
        "name": "Bajaj Allianz Personal Accident Insurance",
        "insurer_name": "Bajaj Allianz General Insurance",
        "category": "personal_accident",
        "type": "personal_accident",
        "sum_insured_min": L(1),
        "sum_insured_max": Cr(5),
        "premium_range_min": 1800,
        "premium_range_max": 25000,
        "key_features": [
            "Accidental death",
            "Permanent total and partial disability",
            "Temporary total disability",
            "Broken bones benefit",
            "Burn injury cover",
        ],
        "exclusion_count": 7,
        "sub_limit_count": 2,
        "waiting_periods": {"pre_existing": 0, "specific": 0, "initial": 0},
        "copay_structure": "NA",
        "room_rent_limit": "NA",
        "eazr_score": 7.8,
    },
]


# ── Cypher ─────────────────────────────────────────────────────────────────────

_MERGE_PRODUCT = """
MERGE (p:Product {name: $name})
SET
  p.insurer_name        = $insurer_name,
  p.category            = $category,
  p.type                = $type,
  p.sum_insured_min     = $sum_insured_min,
  p.sum_insured_max     = $sum_insured_max,
  p.premium_range_min   = $premium_range_min,
  p.premium_range_max   = $premium_range_max,
  p.key_features        = $key_features,
  p.exclusion_count     = $exclusion_count,
  p.sub_limit_count     = $sub_limit_count,
  p.waiting_periods     = $waiting_periods,
  p.copay_structure     = $copay_structure,
  p.room_rent_limit     = $room_rent_limit,
  p.eazr_score          = $eazr_score,
  p.updated_at          = datetime()
RETURN p.name AS name
"""

_MERGE_OFFERS_REL = """
MATCH (i:Insurer {name: $insurer_name})
MATCH (p:Product {name: $product_name})
MERGE (i)-[:OFFERS]->(p)
"""


async def seed_products(client: Neo4jClient) -> None:
    """
    MERGE all Product nodes and OFFERS relationships into Neo4j.
    Idempotent — safe to re-run.
    """
    logger.info("seed_products_start", count=len(PRODUCTS))

    # Prepare serialisable params (convert nested dicts/lists to strings where needed)
    product_params = []
    for p in PRODUCTS:
        params = dict(p)
        # Neo4j can store lists of strings natively; dicts need to be stringified
        params["waiting_periods"] = str(p.get("waiting_periods", {}))
        # Remove non-schema keys that we don't want in Product nodes
        for extra_key in [
            "restore_benefit", "multiplier_benefit", "wellness_benefits", "unlimited_restore",
            "lock_the_clock", "global_cover", "health_returns", "wellness_integration",
            "vitality_program", "zero_copay", "digital_claims", "zero_dep", "paperless",
            "digital", "cashless_garages", "cashless_approval_mins", "claim_approval_hrs",
            "better_half_benefit", "joint_life", "return_of_premium", "whole_life_option",
            "special_exit_value", "ci_conditions_covered", "unlimited_si", "fund_options",
            "lock_in_years", "annual_premium_above_2_5L_taxable_gains", "plan_options",
            "irr_approx", "note", "target_segment", "min_entry_age", "max_entry_age",
            "age_limit", "government_backed", "mandatory", "guaranteed_returns",
            "digital_score", "chronic_management",
        ]:
            params.pop(extra_key, None)
        product_params.append(params)

    succeeded = await client.execute_batch(
        _MERGE_PRODUCT,
        param_list=product_params,
        query_name="seed_products",
    )
    logger.info("seed_products_nodes_complete", succeeded=succeeded, total=len(PRODUCTS))

    # Create OFFERS relationships
    rel_params = [
        {"insurer_name": p["insurer_name"], "product_name": p["name"]}
        for p in PRODUCTS
    ]
    rel_ok = await client.execute_batch(
        _MERGE_OFFERS_REL,
        param_list=rel_params,
        query_name="seed_offers_relationships",
    )
    logger.info("seed_offers_relationships_complete", succeeded=rel_ok, total=len(rel_params))
